-- Type News Vercel/Supabase development schema.
-- Run this in the Supabase development project, not in Firebase or the production TypeNews project.

create extension if not exists pgcrypto;
create extension if not exists citext;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  supabase_user_id uuid unique references auth.users(id) on delete set null,
  firebase_uid text unique,
  google_sub text unique,
  email citext,
  display_name text,
  display_name_lower text,
  max_cpm integer not null default 0 check (max_cpm >= 0),
  total_typing_count integer not null default 0 check (total_typing_count >= 0),
  preferences jsonb not null default '{}'::jsonb,
  role text not null default 'user' check (role in ('user', 'admin')),
  firebase_created_at timestamptz,
  firebase_last_sign_in_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.monthly_stats (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  month_id text not null check (month_id ~ '^[0-9]{6}$'),
  typing_count integer not null default 0 check (typing_count >= 0),
  nickname text,
  email citext,
  updated_at_source timestamptz,
  source_path text unique,
  raw_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (profile_id, month_id)
);

create table if not exists public.typing_results (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  month_id text not null check (month_id ~ '^[0-9]{6}$'),
  mode text not null check (mode in ('short', 'long', 'word', 'news')),
  accuracy integer not null check (accuracy between 0 and 100),
  cpm integer not null check (cpm >= 0 and cpm <= 5000),
  counted_for_ranking boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.suspicious_records (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  firebase_uid text,
  record_id text,
  source_path text unique,
  recorded_at timestamptz,
  record_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists profiles_google_sub_idx on public.profiles (google_sub);
create index if not exists profiles_firebase_uid_idx on public.profiles (firebase_uid);
create index if not exists monthly_stats_month_rank_idx on public.monthly_stats (month_id, typing_count desc, updated_at desc);
create index if not exists typing_results_profile_created_idx on public.typing_results (profile_id, created_at desc);
create index if not exists suspicious_records_recorded_at_idx on public.suspicious_records (recorded_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists monthly_stats_touch_updated_at on public.monthly_stats;
create trigger monthly_stats_touch_updated_at
before update on public.monthly_stats
for each row execute function public.touch_updated_at();

create or replace function public.current_profile_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id
  from public.profiles
  where supabase_user_id = auth.uid()
  limit 1
$$;

create or replace function public.link_current_google_identity()
returns public.profiles
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_email text;
  v_google_sub text;
  v_display_name text;
  v_profile public.profiles;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select
    u.email,
    coalesce(
      u.raw_user_meta_data ->> 'full_name',
      u.raw_user_meta_data ->> 'name',
      u.raw_user_meta_data ->> 'nickname'
    )
  into v_email, v_display_name
  from auth.users u
  where u.id = v_user_id;

  select coalesce(i.identity_data ->> 'sub', i.id)
  into v_google_sub
  from auth.identities i
  where i.user_id = v_user_id
    and i.provider = 'google'
  order by i.created_at asc
  limit 1;

  select *
  into v_profile
  from public.profiles p
  where p.supabase_user_id = v_user_id
     or (v_google_sub is not null and p.google_sub = v_google_sub)
     or (v_email is not null and p.email = v_email)
  order by
    case when p.supabase_user_id = v_user_id then 0 else 1 end,
    p.created_at asc
  limit 1;

  if found then
    update public.profiles
    set
      supabase_user_id = v_user_id,
      google_sub = coalesce(public.profiles.google_sub, v_google_sub),
      email = coalesce(public.profiles.email, v_email),
      display_name = coalesce(public.profiles.display_name, v_display_name, v_email),
      display_name_lower = lower(coalesce(public.profiles.display_name, v_display_name, v_email))
    where id = v_profile.id
    returning * into v_profile;
  else
    insert into public.profiles (
      supabase_user_id,
      google_sub,
      email,
      display_name,
      display_name_lower
    )
    values (
      v_user_id,
      v_google_sub,
      v_email,
      coalesce(v_display_name, v_email, '익명'),
      lower(coalesce(v_display_name, v_email, '익명'))
    )
    returning * into v_profile;
  end if;

  return v_profile;
end;
$$;

create or replace function public.record_typing_result(
  p_month_id text,
  p_mode text,
  p_accuracy integer,
  p_cpm integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if p_month_id !~ '^[0-9]{6}$' then
    raise exception 'Invalid month_id';
  end if;

  if p_mode not in ('short', 'long', 'word', 'news') then
    raise exception 'Invalid mode';
  end if;

  if p_accuracy < 80 or p_accuracy > 100 then
    return;
  end if;

  if p_cpm < 0 or p_cpm > 5000 then
    return;
  end if;

  select public.current_profile_id() into v_profile_id;

  if v_profile_id is null then
    select id into v_profile_id
    from public.link_current_google_identity();
  end if;

  insert into public.typing_results (profile_id, month_id, mode, accuracy, cpm)
  values (v_profile_id, p_month_id, p_mode, p_accuracy, p_cpm);

  insert into public.monthly_stats (profile_id, month_id, typing_count)
  values (v_profile_id, p_month_id, 1)
  on conflict (profile_id, month_id)
  do update set typing_count = public.monthly_stats.typing_count + 1;

  update public.profiles
  set
    total_typing_count = total_typing_count + 1,
    max_cpm = greatest(max_cpm, p_cpm)
  where id = v_profile_id;
end;
$$;

create or replace function public.get_monthly_ranking(p_month_id text, p_limit integer default 50)
returns table (
  profile_id uuid,
  display_name text,
  typing_count integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id as profile_id,
    coalesce(nullif(ms.nickname, ''), nullif(p.display_name, ''), '익명') as display_name,
    ms.typing_count
  from public.monthly_stats ms
  join public.profiles p on p.id = ms.profile_id
  where ms.month_id = p_month_id
  order by ms.typing_count desc, ms.updated_at desc, p.created_at asc
  limit least(greatest(coalesce(p_limit, 50), 1), 100)
$$;

create or replace function public.get_my_typing_summary(p_month_id text)
returns table (
  total_typing_count integer,
  max_cpm integer,
  monthly_score integer
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
begin
  if auth.uid() is null then
    return query select 0, 0, 0;
    return;
  end if;

  select public.current_profile_id() into v_profile_id;

  if v_profile_id is null then
    return query select 0, 0, 0;
    return;
  end if;

  return query
  select
    p.total_typing_count,
    p.max_cpm,
    coalesce(ms.typing_count, 0)
  from public.profiles p
  left join public.monthly_stats ms
    on ms.profile_id = p.id
   and ms.month_id = p_month_id
  where p.id = v_profile_id;
end;
$$;

alter table public.profiles enable row level security;
alter table public.monthly_stats enable row level security;
alter table public.typing_results enable row level security;
alter table public.suspicious_records enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (supabase_user_id = auth.uid());

drop policy if exists "profiles_update_own_preferences" on public.profiles;
create policy "profiles_update_own_preferences"
on public.profiles for update
to authenticated
using (supabase_user_id = auth.uid())
with check (supabase_user_id = auth.uid());

drop policy if exists "monthly_stats_select_own" on public.monthly_stats;
create policy "monthly_stats_select_own"
on public.monthly_stats for select
to authenticated
using (profile_id = public.current_profile_id());

drop policy if exists "typing_results_select_own" on public.typing_results;
create policy "typing_results_select_own"
on public.typing_results for select
to authenticated
using (profile_id = public.current_profile_id());

revoke all on public.profiles from anon;
revoke all on public.monthly_stats from anon;
revoke all on public.typing_results from anon;
revoke all on public.suspicious_records from anon;

grant usage on schema public to anon, authenticated, service_role;
grant select on public.profiles to authenticated;
grant select on public.monthly_stats to authenticated;
grant select on public.typing_results to authenticated;
grant execute on function public.link_current_google_identity() to authenticated;
grant execute on function public.record_typing_result(text, text, integer, integer) to authenticated;
grant execute on function public.get_monthly_ranking(text, integer) to anon, authenticated;
grant execute on function public.get_my_typing_summary(text) to authenticated;

notify pgrst, 'reload schema';
