-- 부정행위(매크로/어뷰징) 탐지 구조.
--
-- 설계 원칙
--   1. 원시 이벤트(문장별 로그, 키로그)를 적재하지 않는다.
--      행 수가 "완료한 문장 수"에 비례하면 데이터가 무한히 늘어난다.
--   2. 클라이언트는 세션 단위 누적 집계만 올리고, 서버가 그 한 행을 덮어쓴다.
--      행 수는 "세션 수"에만 비례하고, 재전송해도 중복이 생기지 않는다.
--   3. 판정은 서버에서 한다. 룰에 걸린 경우에만 abuse_signals에 남는다.
--      같은 세션에서 같은 룰이 반복되면 새 행이 아니라 카운터만 올린다.
--   4. 클라이언트 집계는 조작될 수 있으므로, 서버 시각으로만 만들어지는
--      typing_results.created_at 간격도 함께 본다. (evaluate_server_side_signals)

-- Firestore에서 넘어온 기존 테이블은 참고용으로만 남긴다. 새 기록은 쓰지 않는다.
comment on table public.suspicious_records is
  'LEGACY: Firestore suspiciousRecords 이관 데이터. 신규 탐지는 abuse_signals를 쓴다. 이관 검증이 끝나면 삭제 가능.';

create table if not exists public.typing_sessions (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  -- 클라이언트가 만든 세션 식별자. 탭 하나가 살아 있는 동안 유지된다.
  session_key uuid not null,
  started_at timestamptz not null,
  last_seen_at timestamptz not null default now(),

  sentence_count integer not null default 0 check (sentence_count >= 0),
  typed_chars bigint not null default 0 check (typed_chars >= 0),
  -- 실제로 타이핑한 시간의 합. 창을 켜두기만 한 시간은 빠진다.
  active_ms bigint not null default 0 check (active_ms >= 0),

  -- 평균과 표준편차를 서버에서 뽑기 위한 누적값. 개별 기록은 남기지 않는다.
  cpm_sum bigint not null default 0 check (cpm_sum >= 0),
  cpm_sq_sum numeric not null default 0 check (cpm_sq_sum >= 0),
  cpm_max integer not null default 0 check (cpm_max >= 0),
  accuracy_sum bigint not null default 0 check (accuracy_sum >= 0),

  backspace_count integer not null default 0 check (backspace_count >= 0),
  paste_attempts integer not null default 0 check (paste_attempts >= 0),
  -- 창이 포커스를 잃은 상태에서 입력이 들어온 횟수.
  blurred_input_count integer not null default 0 check (blurred_input_count >= 0),

  -- 한글 문장 중 IME 조합 이벤트가 한 번이라도 있었던 문장 수.
  -- 사람이 한글을 치면 반드시 조합이 일어난다. 값이 0에 가까우면 주입 입력이다.
  hangul_sentence_count integer not null default 0 check (hangul_sentence_count >= 0),
  composed_sentence_count integer not null default 0 check (composed_sentence_count >= 0),

  -- 키 간격(ms) 분포. 사람은 편차가 크고 매크로는 균일하다.
  keystroke_count integer not null default 0 check (keystroke_count >= 0),
  interval_sum bigint not null default 0 check (interval_sum >= 0),
  interval_sq_sum numeric not null default 0 check (interval_sq_sum >= 0),

  user_agent text,
  created_at timestamptz not null default now(),
  unique (profile_id, session_key)
);

comment on table public.typing_sessions is
  '세션당 한 행만 유지되는 타이핑 행동 집계. 문장별 원시 로그는 저장하지 않는다.';

create table if not exists public.abuse_signals (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  session_id bigint references public.typing_sessions(id) on delete cascade,
  rule_code text not null,
  -- 1 관찰 / 2 의심 / 3 강한 의심
  severity smallint not null check (severity between 1 and 3),
  occurrence_count integer not null default 1 check (occurrence_count > 0),
  -- 판정 근거가 된 수치만 담는다. 문장 본문은 절대 담지 않는다.
  evidence jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  -- 관리자가 확인 처리하면 워치리스트에서 내려간다.
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null,
  review_note text,
  unique (profile_id, session_id, rule_code)
);

comment on table public.abuse_signals is
  '룰에 걸린 경우에만 생기는 탐지 신호. 같은 세션의 같은 룰은 카운터만 올린다.';

create index if not exists typing_sessions_profile_seen_idx
  on public.typing_sessions (profile_id, last_seen_at desc);
create index if not exists typing_sessions_last_seen_idx
  on public.typing_sessions (last_seen_at);
create index if not exists abuse_signals_open_idx
  on public.abuse_signals (last_seen_at desc) where reviewed_at is null;
create index if not exists abuse_signals_profile_idx
  on public.abuse_signals (profile_id, last_seen_at desc);

-- 세션과 무관한 신호(서버 시각 기반)는 session_id가 null이다.
-- NULL은 UNIQUE 제약에서 서로 다른 값으로 취급되므로 부분 인덱스로 따로 막는다.
create unique index if not exists abuse_signals_profile_rule_no_session_idx
  on public.abuse_signals (profile_id, rule_code) where session_id is null;

-- ---------------------------------------------------------------------------
-- 권한 도우미
-- ---------------------------------------------------------------------------

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where supabase_user_id = auth.uid()
      and role = 'admin'
  )
$$;

-- ---------------------------------------------------------------------------
-- 신호 기록
-- ---------------------------------------------------------------------------

create or replace function public.raise_abuse_signal(
  p_profile_id uuid,
  p_session_id bigint,
  p_rule_code text,
  p_severity smallint,
  p_evidence jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_updated integer;
begin
  -- session_id가 null일 수 있어서 on conflict 대신 직접 upsert 한다.
  -- `is not distinct from`이라야 null끼리도 같은 행으로 본다.
  update public.abuse_signals
  set
    occurrence_count = occurrence_count + 1,
    severity = p_severity,
    evidence = coalesce(p_evidence, '{}'::jsonb),
    last_seen_at = now(),
    -- 관리자가 확인 처리한 건은 일주일간 다시 올라오지 않는다.
    reviewed_at = case when reviewed_at < now() - interval '7 days' then null else reviewed_at end
  where profile_id = p_profile_id
    and rule_code = p_rule_code
    and session_id is not distinct from p_session_id;

  get diagnostics v_updated = row_count;
  if v_updated > 0 then
    return;
  end if;

  insert into public.abuse_signals (profile_id, session_id, rule_code, severity, evidence)
  values (p_profile_id, p_session_id, p_rule_code, p_severity, coalesce(p_evidence, '{}'::jsonb));
exception
  when unique_violation then
    -- 같은 순간에 다른 탭이 먼저 넣은 경우. 카운터만 올리고 끝낸다.
    update public.abuse_signals
    set occurrence_count = occurrence_count + 1, last_seen_at = now()
    where profile_id = p_profile_id
      and rule_code = p_rule_code
      and session_id is not distinct from p_session_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 룰 평가 (클라이언트 집계 기반)
-- ---------------------------------------------------------------------------

create or replace function public.evaluate_session_signals(p_session_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.typing_sessions;
  v_avg_cpm numeric;
  v_cpm_stddev numeric;
  v_avg_accuracy numeric;
  v_avg_interval numeric;
  v_interval_stddev numeric;
  -- 변동계수. 평균 대비 흔들림의 정도라 타속이 빠르든 느리든 비교가 된다.
  v_interval_cv numeric;
  v_composition_ratio numeric;
  v_session_ms numeric;
begin
  select * into s from public.typing_sessions where id = p_session_id;
  if not found or s.sentence_count = 0 then
    return;
  end if;

  v_avg_cpm := s.cpm_sum::numeric / s.sentence_count;
  v_avg_accuracy := s.accuracy_sum::numeric / s.sentence_count;
  v_cpm_stddev := sqrt(greatest(s.cpm_sq_sum / s.sentence_count - v_avg_cpm ^ 2, 0));
  v_session_ms := extract(epoch from (s.last_seen_at - s.started_at)) * 1000;

  if s.keystroke_count >= 2 then
    v_avg_interval := s.interval_sum::numeric / s.keystroke_count;
    v_interval_stddev := sqrt(greatest(s.interval_sq_sum / s.keystroke_count - v_avg_interval ^ 2, 0));
    v_interval_cv := case when v_avg_interval > 0 then v_interval_stddev / v_avg_interval end;
  end if;

  if s.hangul_sentence_count > 0 then
    v_composition_ratio := s.composed_sentence_count::numeric / s.hangul_sentence_count;
  end if;

  -- 한글을 쳤는데 IME 조합이 거의 없었다. 사람 손으로는 나올 수 없는 패턴이다.
  if s.hangul_sentence_count >= 5 and v_composition_ratio < 0.2 then
    perform public.raise_abuse_signal(
      s.profile_id, s.id, 'NO_IME_COMPOSITION', 3,
      jsonb_build_object(
        'hangul_sentences', s.hangul_sentence_count,
        'composed_sentences', s.composed_sentence_count,
        'ratio', round(v_composition_ratio, 3)
      )
    );
  end if;

  -- 문장은 계속 완료되는데 실제 키 이벤트가 거의 없다. 값이 직접 주입되고 있다.
  if s.sentence_count >= 10 and s.keystroke_count < s.typed_chars / 4 then
    perform public.raise_abuse_signal(
      s.profile_id, s.id, 'NO_KEY_EVENTS', 3,
      jsonb_build_object(
        'sentences', s.sentence_count,
        'keystrokes', s.keystroke_count,
        'typed_chars', s.typed_chars
      )
    );
  end if;

  -- 창이 백그라운드인데 입력이 들어왔다.
  if s.blurred_input_count >= 10 then
    perform public.raise_abuse_signal(
      s.profile_id, s.id, 'BACKGROUND_INPUT', 3,
      jsonb_build_object('blurred_inputs', s.blurred_input_count)
    );
  end if;

  -- 키 간격이 지나치게 균일하다.
  if s.keystroke_count >= 200 and v_interval_cv is not null and v_interval_cv < 0.15 then
    perform public.raise_abuse_signal(
      s.profile_id, s.id, 'UNIFORM_KEY_RHYTHM', 3,
      jsonb_build_object(
        'keystrokes', s.keystroke_count,
        'avg_interval_ms', round(v_avg_interval, 1),
        'interval_cv', round(v_interval_cv, 3)
      )
    );
  end if;

  -- 한 번도 고쳐 치지 않고 거의 완벽하다.
  if s.sentence_count >= 20 and s.backspace_count = 0 and v_avg_accuracy >= 99 then
    perform public.raise_abuse_signal(
      s.profile_id, s.id, 'NO_CORRECTION', 2,
      jsonb_build_object('sentences', s.sentence_count, 'avg_accuracy', round(v_avg_accuracy, 1))
    );
  end if;

  -- 순간 최고 속도가 사람 범위를 벗어난다.
  if s.cpm_max > 1200 and v_avg_accuracy >= 98 then
    perform public.raise_abuse_signal(
      s.profile_id, s.id, 'SPEED_SPIKE', 2,
      jsonb_build_object('max_cpm', s.cpm_max, 'avg_accuracy', round(v_avg_accuracy, 1))
    );
  end if;

  -- 문장이 바뀌어도 속도가 거의 변하지 않는다. (원본 타입뉴스의 표준편차 룰)
  if s.sentence_count >= 5 and v_cpm_stddev < 50 and v_avg_accuracy >= 95 then
    perform public.raise_abuse_signal(
      s.profile_id, s.id, 'FLAT_CPM_VARIANCE', 2,
      jsonb_build_object(
        'sentences', s.sentence_count,
        'avg_cpm', round(v_avg_cpm, 1),
        'cpm_stddev', round(v_cpm_stddev, 1)
      )
    );
  end if;

  -- 붙여넣기를 계속 시도한다.
  if s.paste_attempts >= 5 then
    perform public.raise_abuse_signal(
      s.profile_id, s.id, 'PASTE_ATTEMPT', 1,
      jsonb_build_object('attempts', s.paste_attempts)
    );
  end if;

  -- 쉬지 않고 5시간 넘게 고정확도를 유지한다.
  if v_session_ms >= 5 * 60 * 60 * 1000 and v_avg_accuracy >= 95 then
    perform public.raise_abuse_signal(
      s.profile_id, s.id, 'MARATHON_SESSION', 1,
      jsonb_build_object(
        'session_hours', round(v_session_ms / 3600000, 1),
        'avg_accuracy', round(v_avg_accuracy, 1)
      )
    );
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 룰 평가 (서버 시각 기반. 클라이언트가 조작할 수 없는 신호)
-- ---------------------------------------------------------------------------

create or replace function public.evaluate_server_side_signals(p_profile_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
  v_avg_gap numeric;
  v_stddev_gap numeric;
  v_cv numeric;
begin
  -- 점수가 적립된 시각의 간격만 본다. created_at은 서버가 찍으므로 위조가 안 된다.
  with recent as (
    select created_at
    from public.typing_results
    where profile_id = p_profile_id
      and created_at > now() - interval '2 hours'
    order by created_at desc
    limit 120
  ),
  gaps as (
    select extract(epoch from (created_at - lag(created_at) over (order by created_at))) as gap
    from recent
  )
  select count(*), avg(gap), stddev_pop(gap)
  into v_count, v_avg_gap, v_stddev_gap
  from gaps
  where gap is not null and gap between 0.05 and 600;

  if v_count < 30 or v_avg_gap is null or v_avg_gap <= 0 then
    return;
  end if;

  v_cv := v_stddev_gap / v_avg_gap;

  -- 문장 길이가 제각각인데 제출 간격이 일정하다면 사람 손이 아니다.
  if v_cv < 0.12 then
    perform public.raise_abuse_signal(
      p_profile_id, null, 'UNIFORM_SUBMIT_INTERVAL', 3,
      jsonb_build_object(
        'samples', v_count,
        'avg_gap_sec', round(v_avg_gap, 2),
        'gap_cv', round(v_cv, 3)
      )
    );
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 클라이언트 진입점
-- ---------------------------------------------------------------------------

create or replace function public.report_typing_session(
  p_session_key uuid,
  p_started_at timestamptz,
  p_metrics jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
  v_session_id bigint;
  v_sentence_count integer;
begin
  if auth.uid() is null then
    return;
  end if;

  select public.current_profile_id() into v_profile_id;
  if v_profile_id is null then
    return;
  end if;

  v_sentence_count := least(greatest(coalesce((p_metrics ->> 'sentenceCount')::integer, 0), 0), 100000);
  if v_sentence_count = 0 then
    return;
  end if;

  -- 누적 스냅샷을 통째로 덮어쓴다. 재전송해도 중복 집계가 되지 않는다.
  -- 값은 전부 상한을 씌운다. 조작된 숫자로 통계를 망가뜨리지 못하게.
  insert into public.typing_sessions as ts (
    profile_id, session_key, started_at, last_seen_at,
    sentence_count, typed_chars, active_ms,
    cpm_sum, cpm_sq_sum, cpm_max, accuracy_sum,
    backspace_count, paste_attempts, blurred_input_count,
    hangul_sentence_count, composed_sentence_count,
    keystroke_count, interval_sum, interval_sq_sum,
    user_agent
  )
  values (
    v_profile_id,
    p_session_key,
    least(coalesce(p_started_at, now()), now()),
    now(),
    v_sentence_count,
    least(greatest(coalesce((p_metrics ->> 'typedChars')::bigint, 0), 0), 100000000),
    least(greatest(coalesce((p_metrics ->> 'activeMs')::bigint, 0), 0), 86400000),
    least(greatest(coalesce((p_metrics ->> 'cpmSum')::bigint, 0), 0), 500000000),
    least(greatest(coalesce((p_metrics ->> 'cpmSqSum')::numeric, 0), 0), 1e15),
    least(greatest(coalesce((p_metrics ->> 'cpmMax')::integer, 0), 0), 100000),
    least(greatest(coalesce((p_metrics ->> 'accuracySum')::bigint, 0), 0), 10000000),
    least(greatest(coalesce((p_metrics ->> 'backspaceCount')::integer, 0), 0), 10000000),
    least(greatest(coalesce((p_metrics ->> 'pasteAttempts')::integer, 0), 0), 1000000),
    least(greatest(coalesce((p_metrics ->> 'blurredInputCount')::integer, 0), 0), 1000000),
    least(greatest(coalesce((p_metrics ->> 'hangulSentenceCount')::integer, 0), 0), 100000),
    least(greatest(coalesce((p_metrics ->> 'composedSentenceCount')::integer, 0), 0), 100000),
    least(greatest(coalesce((p_metrics ->> 'keystrokeCount')::integer, 0), 0), 100000000),
    least(greatest(coalesce((p_metrics ->> 'intervalSum')::bigint, 0), 0), 86400000),
    least(greatest(coalesce((p_metrics ->> 'intervalSqSum')::numeric, 0), 0), 1e15),
    left(coalesce(p_metrics ->> 'userAgent', ''), 300)
  )
  on conflict (profile_id, session_key) do update
  set
    last_seen_at = now(),
    sentence_count = greatest(ts.sentence_count, excluded.sentence_count),
    typed_chars = greatest(ts.typed_chars, excluded.typed_chars),
    active_ms = greatest(ts.active_ms, excluded.active_ms),
    cpm_sum = greatest(ts.cpm_sum, excluded.cpm_sum),
    cpm_sq_sum = greatest(ts.cpm_sq_sum, excluded.cpm_sq_sum),
    cpm_max = greatest(ts.cpm_max, excluded.cpm_max),
    accuracy_sum = greatest(ts.accuracy_sum, excluded.accuracy_sum),
    backspace_count = greatest(ts.backspace_count, excluded.backspace_count),
    paste_attempts = greatest(ts.paste_attempts, excluded.paste_attempts),
    blurred_input_count = greatest(ts.blurred_input_count, excluded.blurred_input_count),
    hangul_sentence_count = greatest(ts.hangul_sentence_count, excluded.hangul_sentence_count),
    composed_sentence_count = greatest(ts.composed_sentence_count, excluded.composed_sentence_count),
    keystroke_count = greatest(ts.keystroke_count, excluded.keystroke_count),
    interval_sum = greatest(ts.interval_sum, excluded.interval_sum),
    interval_sq_sum = greatest(ts.interval_sq_sum, excluded.interval_sq_sum),
    user_agent = coalesce(nullif(excluded.user_agent, ''), ts.user_agent)
  returning ts.id into v_session_id;

  perform public.evaluate_session_signals(v_session_id);
  perform public.evaluate_server_side_signals(v_profile_id);
end;
$$;

-- ---------------------------------------------------------------------------
-- 관리자 조회
-- ---------------------------------------------------------------------------

create or replace function public.get_abuse_watchlist(
  p_since_days integer default 30,
  p_limit integer default 50
)
returns table (
  profile_id uuid,
  display_name text,
  email text,
  risk_score integer,
  max_severity smallint,
  signal_count integer,
  rule_codes text[],
  last_seen_at timestamptz,
  monthly_typing_count integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    coalesce(nullif(p.display_name, ''), '익명'),
    p.email::text,
    -- 심각도가 높을수록 가중치를 크게. 반복 횟수는 로그로 눌러서 한 세션이 순위를 독식하지 않게.
    sum(a.severity * a.severity * (1 + ln(a.occurrence_count)))::integer,
    max(a.severity),
    count(*)::integer,
    array_agg(distinct a.rule_code order by a.rule_code),
    max(a.last_seen_at),
    coalesce(max(ms.typing_count), 0)
  from public.abuse_signals a
  join public.profiles p on p.id = a.profile_id
  left join public.monthly_stats ms
    on ms.profile_id = p.id
   and ms.month_id = to_char(now() at time zone 'Asia/Seoul', 'YYYYMM')
  where a.reviewed_at is null
    and a.last_seen_at > now() - make_interval(days => greatest(coalesce(p_since_days, 30), 1))
    and public.is_admin()
  group by p.id, p.display_name, p.email
  order by 4 desc, 8 desc
  limit least(greatest(coalesce(p_limit, 50), 1), 500)
$$;

create or replace function public.review_abuse_signals(
  p_profile_id uuid,
  p_note text default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reviewer uuid;
  v_updated integer;
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;

  select public.current_profile_id() into v_reviewer;

  update public.abuse_signals
  set reviewed_at = now(), reviewed_by = v_reviewer, review_note = p_note
  where profile_id = p_profile_id and reviewed_at is null;

  get diagnostics v_updated = row_count;
  return v_updated;
end;
$$;

-- ---------------------------------------------------------------------------
-- 보존 정책
-- ---------------------------------------------------------------------------

-- 오래된 집계를 지운다. pg_cron으로 하루 한 번 돌리는 것을 권장한다.
--   select cron.schedule('prune-integrity', '20 4 * * *', $$select public.prune_integrity_data()$$);
create or replace function public.prune_integrity_data(
  p_session_days integer default 120,
  p_reviewed_signal_days integer default 400
)
returns table (deleted_sessions integer, deleted_signals integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sessions integer;
  v_signals integer;
begin
  -- 신호가 붙지 않은 평범한 세션만 지운다. 근거가 남아 있어야 할 세션은 보존.
  delete from public.typing_sessions ts
  where ts.last_seen_at < now() - make_interval(days => greatest(p_session_days, 7))
    and not exists (select 1 from public.abuse_signals a where a.session_id = ts.id);
  get diagnostics v_sessions = row_count;

  delete from public.abuse_signals
  where reviewed_at is not null
    and reviewed_at < now() - make_interval(days => greatest(p_reviewed_signal_days, 30));
  get diagnostics v_signals = row_count;

  return query select v_sessions, v_signals;
end;
$$;

-- ---------------------------------------------------------------------------
-- RLS / 권한
-- ---------------------------------------------------------------------------

alter table public.typing_sessions enable row level security;
alter table public.abuse_signals enable row level security;

-- 탐지 결과는 본인도 볼 수 없다. 어떤 룰에 걸렸는지 알면 회피가 쉬워진다.
drop policy if exists "typing_sessions_admin_select" on public.typing_sessions;
create policy "typing_sessions_admin_select"
on public.typing_sessions for select
to authenticated
using (public.is_admin());

drop policy if exists "abuse_signals_admin_select" on public.abuse_signals;
create policy "abuse_signals_admin_select"
on public.abuse_signals for select
to authenticated
using (public.is_admin());

revoke all on public.typing_sessions from anon, authenticated;
revoke all on public.abuse_signals from anon, authenticated;
grant select on public.typing_sessions to authenticated;
grant select on public.abuse_signals to authenticated;

-- 내부 함수는 클라이언트에 노출하지 않는다.
revoke all on function public.raise_abuse_signal(uuid, bigint, text, smallint, jsonb) from public, anon, authenticated;
revoke all on function public.evaluate_session_signals(bigint) from public, anon, authenticated;
revoke all on function public.evaluate_server_side_signals(uuid) from public, anon, authenticated;
revoke all on function public.prune_integrity_data(integer, integer) from public, anon, authenticated;

grant execute on function public.is_admin() to authenticated;
grant execute on function public.report_typing_session(uuid, timestamptz, jsonb) to authenticated;
grant execute on function public.get_abuse_watchlist(integer, integer) to authenticated;
grant execute on function public.review_abuse_signals(uuid, text) to authenticated;

notify pgrst, 'reload schema';
