-- 관리 기능의 데이터 계층.
--   1) 닉네임 변경
--   2) 사용자 문장 추가 요청 + 관리자 심사
--   3) 관리자가 직접 관리하는 문장
--   4) 이벤트 경품
--
-- ⚠️ 권한은 전부 서버에서 판정한다.
-- 관리자 페이지를 비밀번호로 가리더라도 그것은 오조작 방지용 잠금일 뿐이다.
-- 데이터를 지키는 것은 아래 RLS와 security definer 함수의 is_admin() 검사다.

-- ---------------------------------------------------------------------------
-- 닉네임
-- ---------------------------------------------------------------------------

create or replace function public.update_my_display_name(p_display_name text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
  v_name text := btrim(coalesce(p_display_name, ''));
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if char_length(v_name) < 1 or char_length(v_name) > 12 then
    raise exception '닉네임은 1~12자여야 합니다';
  end if;

  -- 보이지 않는 문자로 남을 사칭하거나 줄을 깨뜨리지 못하게 막는다.
  if v_name ~ ('[' || chr(8203) || chr(8204) || chr(8205) || chr(8206) || chr(8207)
                   || chr(160) || chr(65279) || ']')
     or v_name ~ '[[:cntrl:]]'
  then
    raise exception '사용할 수 없는 문자가 있습니다';
  end if;

  select public.current_profile_id() into v_profile_id;
  if v_profile_id is null then
    raise exception 'Profile not found';
  end if;

  if exists (
    select 1 from public.profiles
    where display_name_lower = lower(v_name) and id <> v_profile_id
  ) then
    raise exception '이미 사용 중인 닉네임입니다';
  end if;

  update public.profiles
  set display_name = v_name, display_name_lower = lower(v_name)
  where id = v_profile_id;

  -- 랭킹은 monthly_stats.nickname을 우선 쓰므로 이번 달 표시도 맞춰준다.
  update public.monthly_stats
  set nickname = v_name
  where profile_id = v_profile_id
    and month_id = to_char(now() at time zone 'Asia/Seoul', 'YYYYMM');

  return v_name;
end;
$$;

-- ---------------------------------------------------------------------------
-- 문장
-- ---------------------------------------------------------------------------

create table if not exists public.sentences (
  id bigint generated by default as identity primary key,
  language text not null check (language in ('kor', 'eng')),
  mode text not null check (mode in ('short', 'long', 'word')),
  text text not null check (char_length(btrim(text)) between 1 and 400),
  -- 밈이 섞인 묶음에만 넣을 문장인지. 기본 묶음은 밈이 없는 쪽이다.
  is_meme boolean not null default false,
  enabled boolean not null default true,
  -- 사용자 요청에서 온 문장이면 원본을 가리킨다.
  source_request_id bigint,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sentences_pick_idx
  on public.sentences (language, mode, enabled) where enabled;

create table if not exists public.sentence_requests (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  language text not null check (language in ('kor', 'eng')),
  mode text not null check (mode in ('short', 'long', 'word')),
  text text not null check (char_length(btrim(text)) between 1 and 400),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  -- 관리자가 다듬어 반영한 경우 최종 문장을 남긴다.
  reviewed_text text,
  review_note text,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists sentence_requests_pending_idx
  on public.sentence_requests (created_at) where status = 'pending';
create index if not exists sentence_requests_profile_idx
  on public.sentence_requests (profile_id, created_at desc);

drop trigger if exists sentences_touch_updated_at on public.sentences;
create trigger sentences_touch_updated_at
before update on public.sentences
for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- 이벤트 경품
-- ---------------------------------------------------------------------------

create table if not exists public.event_prizes (
  id bigint generated by default as identity primary key,
  name text not null,
  -- 이름이 길어 카드에서 줄여 쓸 때의 원래 표기
  full_name text,
  image_url text,
  link_url text,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

drop trigger if exists event_prizes_touch_updated_at on public.event_prizes;
create trigger event_prizes_touch_updated_at
before update on public.event_prizes
for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- 사용자용 함수
-- ---------------------------------------------------------------------------

create or replace function public.submit_sentence_request(
  p_language text,
  p_mode text,
  p_text text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
  v_text text := btrim(coalesce(p_text, ''));
  v_recent integer;
  v_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if p_language not in ('kor', 'eng') or p_mode not in ('short', 'long', 'word') then
    raise exception '잘못된 언어 또는 모드입니다';
  end if;

  if char_length(v_text) < 2 or char_length(v_text) > 400 then
    raise exception '문장은 2~400자여야 합니다';
  end if;

  select public.current_profile_id() into v_profile_id;
  if v_profile_id is null then
    raise exception 'Profile not found';
  end if;

  -- 하루 20건으로 제한한다. 심사 큐가 한 사람으로 넘치지 않게.
  select count(*) into v_recent
  from public.sentence_requests
  where profile_id = v_profile_id and created_at > now() - interval '1 day';

  if v_recent >= 20 then
    raise exception '하루에 보낼 수 있는 요청을 모두 사용했습니다';
  end if;

  insert into public.sentence_requests (profile_id, language, mode, text)
  values (v_profile_id, p_language, p_mode, v_text)
  returning id into v_id;

  return v_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 관리자용 함수
-- ---------------------------------------------------------------------------

create or replace function public.review_sentence_request(
  p_request_id bigint,
  p_accept boolean,
  p_text text default null,
  p_note text default null,
  p_is_meme boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin uuid;
  v_request public.sentence_requests;
  v_final text;
  v_sentence_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;

  select public.current_profile_id() into v_admin;

  select * into v_request from public.sentence_requests where id = p_request_id;
  if not found then
    raise exception '요청을 찾을 수 없습니다';
  end if;
  if v_request.status <> 'pending' then
    raise exception '이미 처리된 요청입니다';
  end if;

  -- 다듬어서 반영할 수 있다. 넘기지 않으면 원문 그대로.
  v_final := btrim(coalesce(p_text, v_request.text));

  update public.sentence_requests
  set
    status = case when p_accept then 'accepted' else 'rejected' end,
    reviewed_text = case when p_accept then v_final else null end,
    review_note = p_note,
    reviewed_by = v_admin,
    reviewed_at = now()
  where id = p_request_id;

  if not p_accept then
    return null;
  end if;

  insert into public.sentences (language, mode, text, is_meme, source_request_id, created_by)
  values (v_request.language, v_request.mode, v_final, coalesce(p_is_meme, false), p_request_id, v_admin)
  returning id into v_sentence_id;

  return v_sentence_id;
end;
$$;

create or replace function public.get_sentence_requests(
  p_status text default 'pending',
  p_limit integer default 100
)
returns table (
  id bigint,
  display_name text,
  language text,
  mode text,
  text text,
  status text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select r.id, coalesce(nullif(p.display_name, ''), '익명'), r.language, r.mode, r.text, r.status, r.created_at
  from public.sentence_requests r
  join public.profiles p on p.id = r.profile_id
  where public.is_admin()
    and (p_status is null or r.status = p_status)
  order by r.created_at desc
  limit least(greatest(coalesce(p_limit, 100), 1), 500)
$$;

-- ---------------------------------------------------------------------------
-- RLS / 권한
-- ---------------------------------------------------------------------------

alter table public.sentences enable row level security;
alter table public.sentence_requests enable row level security;
alter table public.event_prizes enable row level security;

-- 문장은 누구나 읽는다. 쓰기는 관리자만.
drop policy if exists "sentences_read" on public.sentences;
create policy "sentences_read" on public.sentences
for select to anon, authenticated using (enabled or public.is_admin());

drop policy if exists "sentences_admin_write" on public.sentences;
create policy "sentences_admin_write" on public.sentences
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- 요청은 본인 것만 본다. 관리자는 전부.
drop policy if exists "sentence_requests_own" on public.sentence_requests;
create policy "sentence_requests_own" on public.sentence_requests
for select to authenticated
using (profile_id = public.current_profile_id() or public.is_admin());

drop policy if exists "sentence_requests_admin_write" on public.sentence_requests;
create policy "sentence_requests_admin_write" on public.sentence_requests
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- 경품은 누구나 읽고 관리자만 고친다.
drop policy if exists "event_prizes_read" on public.event_prizes;
create policy "event_prizes_read" on public.event_prizes
for select to anon, authenticated using (enabled or public.is_admin());

drop policy if exists "event_prizes_admin_write" on public.event_prizes;
create policy "event_prizes_admin_write" on public.event_prizes
for all to authenticated using (public.is_admin()) with check (public.is_admin());

revoke all on public.sentences from anon, authenticated;
revoke all on public.sentence_requests from anon, authenticated;
revoke all on public.event_prizes from anon, authenticated;

grant select on public.sentences to anon, authenticated;
grant select on public.event_prizes to anon, authenticated;
grant select on public.sentence_requests to authenticated;
-- 관리자 화면의 직접 편집(추가/수정/삭제)은 RLS가 is_admin()으로 막는다.
grant insert, update, delete on public.sentences to authenticated;
grant insert, update, delete on public.event_prizes to authenticated;
grant update, delete on public.sentence_requests to authenticated;
grant usage on all sequences in schema public to authenticated;

grant execute on function public.update_my_display_name(text) to authenticated;
grant execute on function public.submit_sentence_request(text, text, text) to authenticated;
grant execute on function public.review_sentence_request(bigint, boolean, text, text, boolean) to authenticated;
grant execute on function public.get_sentence_requests(text, integer) to authenticated;

notify pgrst, 'reload schema';
