-- 관리자가 점수를 감점·영점 처리할 수 있게 한다.
--
-- 왜 필요한가:
--   상한으로 거절하는 대신 탐지 신호만 남기는 방향을 택했다(CUTOVER-AUDIT D3-3).
--   그 방식은 "잡은 뒤에 점수를 취소할 수 있어야" 성립한다. 지금은 수단이 없어서
--   어뷰저를 찾아도 워치리스트에 이름만 쌓이고 랭킹은 그대로다.
--
--   typing_results.counted_for_ranking 컬럼이 0001부터 있지만 어디서도 읽지 않는다.
--   랭킹은 monthly_stats.score만 본다. 그래서 그 컬럼을 살리는 대신 monthly_stats를
--   직접 조정하고 이력을 남기는 방식으로 간다.
--
-- ⚠️ 점수 적립 경로(record_typing_result)는 건드리지 않는다. 관리자 전용 함수만 추가한다.

-- ---------------------------------------------------------------------------
-- 조정 이력
-- ---------------------------------------------------------------------------
--
-- 경품이 걸린 랭킹을 손으로 고치는 일이므로 근거가 남아야 한다.
-- "왜 저 사람 점수가 줄었냐"에 답할 수 있어야 하고, 잘못 눌렀을 때 되돌릴 수 있어야 한다.

create table if not exists public.score_adjustments (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  month_id text not null check (month_id ~ '^[0-9]{6}$'),
  -- 조정 전/후 값을 둘 다 남긴다. delta만 남기면 중간에 점수가 더 쌓였을 때
  -- 원래 값을 복원할 수 없다.
  score_before integer not null,
  score_after integer not null,
  reason text not null,
  adjusted_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists score_adjustments_profile_idx
  on public.score_adjustments (profile_id, created_at desc);
create index if not exists score_adjustments_month_idx
  on public.score_adjustments (month_id, created_at desc);

comment on table public.score_adjustments is
  '관리자의 점수 조정 이력. 경품 분쟁에 답하기 위한 근거이므로 지우지 않는다.';

-- ---------------------------------------------------------------------------
-- 조정 함수
-- ---------------------------------------------------------------------------

-- p_new_score를 그대로 넣는다. 영점 처리는 0, 감점은 원하는 값.
-- 상대값(delta)이 아니라 절대값을 받는 이유: 관리자가 화면에서 본 숫자를 그대로
-- 입력하게 하면 착오가 줄고, 동시에 점수가 쌓여도 의도한 결과가 나온다.
create or replace function public.adjust_monthly_score(
  p_profile_id uuid,
  p_month_id text,
  p_new_score integer,
  p_reason text
)
returns table (score_before integer, score_after integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin uuid;
  v_before integer;
  v_reason text := btrim(coalesce(p_reason, ''));
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;

  if p_month_id !~ '^[0-9]{6}$' then
    raise exception '잘못된 month_id입니다';
  end if;

  if p_new_score is null or p_new_score < 0 then
    raise exception '점수는 0 이상이어야 합니다';
  end if;

  -- 근거 없는 조정을 막는다. 나중에 이력을 봤을 때 이유를 알 수 없으면 쓸모가 없다.
  if char_length(v_reason) < 2 then
    raise exception '조정 사유를 남겨야 합니다';
  end if;

  select public.current_profile_id() into v_admin;

  select ms.score into v_before
  from public.monthly_stats ms
  where ms.profile_id = p_profile_id and ms.month_id = p_month_id
  for update;

  if not found then
    raise exception '해당 사용자의 그 달 기록이 없습니다';
  end if;

  update public.monthly_stats
  set score = p_new_score
  where profile_id = p_profile_id and month_id = p_month_id;

  insert into public.score_adjustments
    (profile_id, month_id, score_before, score_after, reason, adjusted_by)
  values
    (p_profile_id, p_month_id, v_before, p_new_score, v_reason, v_admin);

  return query select v_before, p_new_score;
end;
$$;

-- 조정 이력 조회. 특정 사용자만 보려면 p_profile_id를 넘긴다.
create or replace function public.get_score_adjustments(
  p_profile_id uuid default null,
  p_limit integer default 100
)
returns table (
  id bigint,
  profile_id uuid,
  display_name text,
  month_id text,
  score_before integer,
  score_after integer,
  reason text,
  adjusted_by_name text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    a.id,
    a.profile_id,
    coalesce(nullif(p.display_name, ''), '익명'),
    a.month_id,
    a.score_before,
    a.score_after,
    a.reason,
    coalesce(nullif(admin.display_name, ''), '알 수 없음'),
    a.created_at
  from public.score_adjustments a
  join public.profiles p on p.id = a.profile_id
  left join public.profiles admin on admin.id = a.adjusted_by
  where public.is_admin()
    and (p_profile_id is null or a.profile_id = p_profile_id)
  order by a.created_at desc
  limit least(greatest(coalesce(p_limit, 100), 1), 500)
$$;

-- ---------------------------------------------------------------------------
-- RLS / 권한
-- ---------------------------------------------------------------------------

alter table public.score_adjustments enable row level security;

-- 조정 이력은 관리자만 본다. 어떤 근거로 걸렸는지 알면 회피가 쉬워진다.
drop policy if exists "score_adjustments_admin_select" on public.score_adjustments;
create policy "score_adjustments_admin_select"
on public.score_adjustments for select
to authenticated
using (public.is_admin());

revoke all on public.score_adjustments from anon, authenticated;
grant select on public.score_adjustments to authenticated;

revoke all on function public.adjust_monthly_score(uuid, text, integer, text) from public, anon;
revoke all on function public.get_score_adjustments(uuid, integer) from public, anon;
grant execute on function public.adjust_monthly_score(uuid, text, integer, text) to authenticated;
grant execute on function public.get_score_adjustments(uuid, integer) to authenticated;

notify pgrst, 'reload schema';
