-- 월간 경품 추첨 자동화의 데이터 계층.
--
-- 정해진 규칙
--   - 랭킹 마감: 말일 23:59:59 (KST)
--   - 추첨: 다음 달 1일 00:00 (KST)
--   - 주소 회신 기한: 추첨일 + 2일의 23:50 (KST)
--       1회차 1일 00:00 추첨 → 3일 23:50 마감
--       2회차 4일 00:00 재추첨 → 6일 23:50 마감
--   - 등수에 따라 응모권을 나눠 갖고 그중에서 뽑는다 (마블 룰렛과 같은 방식)
--
-- 응모권 배분 — 기존 운영 방식을 그대로 옮긴 것이다.
--
--   | 등수    | 응모권 | 1명 뽑을 때 확률 |
--   |---------|--------|------------------|
--   | 1등     | 8장    | 11.43%           |
--   | 2등     | 5장    | 7.14%            |
--   | 3등     | 3장    | 4.29%            |
--   | 4~10등  | 각 2장 | 각 2.86%         |
--   | 11~50등 | 각 1장 | 각 1.43%         |
--   | 51등~   | 없음   | 후보 아님        |
--
--   총 8 + 5 + 3 + (7x2) + (40x1) = 70장.
--
-- ⚠️ 점수 자체가 아니라 **등수**가 확률을 정한다. 점수가 두 배라고 확률이 두 배가
--    되지는 않는다. 등수는 그 달 최종 순위로 한 번 정하고, 재추첨에서도 바뀌지
--    않는다 — 다른 사람이 당첨됐다고 내 등수가 올라가지는 않는다.
--
-- ⚠️ 점수 적립 경로는 건드리지 않는다. 여기서는 monthly_stats를 읽기만 한다.
--
-- 이 마이그레이션은 DB 계층만 만든다. 메일 발송과 스케줄러는 별도다.
-- 메일: Supabase는 인증 메일만 보낸다. 외부 HTTP API(Resend 등)가 필요하다.
-- 스케줄: pg_cron. 아래 맨 아래에 등록 예시를 적어뒀다.

-- ---------------------------------------------------------------------------
-- 협찬사
-- ---------------------------------------------------------------------------
--
-- 당첨 안내에 "이 경품은 OO의 협찬으로 제공됩니다"를 넣으려면 경품마다 협찬사가
-- 있어야 한다. 관리자 화면 경품 관리 탭에서 입력한다.

alter table public.event_prizes
  add column if not exists sponsor text;

comment on column public.event_prizes.sponsor is
  '협찬사 표기. 당첨 안내 모달과 메일에 그대로 노출된다.';

-- ---------------------------------------------------------------------------
-- 추첨 회차
-- ---------------------------------------------------------------------------

create table if not exists public.prize_draws (
  id bigint generated by default as identity primary key,
  month_id text not null check (month_id ~ '^[0-9]{6}$'),
  drawn_at timestamptz not null default now(),
  -- 추첨 시점의 후보 규모. 나중에 확률을 설명할 수 있어야 한다.
  candidate_count integer not null,
  total_tickets integer not null,
  -- 재추첨도 같은 달에 여러 번 일어난다. 몇 번째 실행인지.
  round integer not null default 1,
  note text,
  unique (month_id, round)
);

comment on table public.prize_draws is
  '월별 추첨 실행 기록. 경품 분쟁에 답하기 위한 근거이므로 지우지 않는다.';

-- ---------------------------------------------------------------------------
-- 당첨자
-- ---------------------------------------------------------------------------
--
-- 상태 기계
--   pending   추첨됨. 주소 입력 대기 (3일)
--   confirmed 주소를 받았다
--   expired   3일이 지나 무효. 재추첨 대상
--   voided    관리자가 취소 (부정행위 등)

create table if not exists public.prize_winners (
  id bigint generated by default as identity primary key,
  draw_id bigint not null references public.prize_draws(id) on delete cascade,
  month_id text not null check (month_id ~ '^[0-9]{6}$'),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  prize_id bigint references public.event_prizes(id) on delete set null,
  -- 경품이 나중에 지워져도 무엇에 당첨됐는지는 남아야 한다.
  prize_name text not null,
  prize_sponsor text,
  -- 추첨 당시의 등수·응모권·전체 응모권. 확률을 그대로 재현할 수 있다.
  score_at_draw integer not null,
  rank_at_draw integer not null,
  tickets_at_draw integer not null,
  total_tickets_at_draw integer not null,
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'expired', 'voided')),
  -- 주소 입력 마감. 지나면 expire_stale_winners가 정리한다.
  respond_by timestamptz not null,
  notified_at timestamptz,
  responded_at timestamptz,
  /* 주소를 어디로 받았는지.
     당첨자가 사이트를 안 쓰고 메일로 회신하는 경우가 있어서, 관리자가 손으로
     "받았음"을 표시할 수 있어야 한다. 그때는 'email'이 된다. */
  response_channel text check (response_channel in ('site', 'email', 'manual')),
  response_note text,
  voided_reason text,
  created_at timestamptz not null default now(),
  -- 같은 달에 같은 사람이 두 경품을 받지 않게 한다.
  unique (month_id, profile_id)
);

create index if not exists prize_winners_pending_idx
  on public.prize_winners (respond_by) where status = 'pending';
create index if not exists prize_winners_profile_idx
  on public.prize_winners (profile_id, created_at desc);
-- 메일을 아직 못 보낸 당첨자를 찾는 경로.
create index if not exists prize_winners_unnotified_idx
  on public.prize_winners (created_at) where notified_at is null and status = 'pending';

-- ---------------------------------------------------------------------------
-- 배송지
-- ---------------------------------------------------------------------------
--
-- ⚠️ 개인정보다. profiles에 붙이지 않는다 — profiles는 랭킹·로그인 경로에서
--    읽히는 테이블이라 실수로 새어 나갈 표면이 넓다.
--    배송이 끝나면 지운다. 아래 purge_delivered_addresses 참고.

create table if not exists public.winner_addresses (
  winner_id bigint primary key references public.prize_winners(id) on delete cascade,
  recipient text not null,
  phone text not null,
  postal_code text not null,
  address1 text not null,
  address2 text,
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists winner_addresses_touch_updated_at on public.winner_addresses;
create trigger winner_addresses_touch_updated_at
before update on public.winner_addresses
for each row execute function public.touch_updated_at();

comment on table public.winner_addresses is
  '경품 배송지. 개인정보이므로 배송 완료 후 purge_delivered_addresses로 파기한다.';

-- ---------------------------------------------------------------------------
-- 추첨 실행
-- ---------------------------------------------------------------------------

/**
 * 등수별 응모권을 나눠 갖고 그중에서 당첨자를 뽑는다.
 *
 * - 등수는 **그 달 최종 순위**로 한 번 매긴다. 재추첨에서도 다시 매기지 않는다.
 *   앞사람이 당첨됐다고 내 등수가 올라가면 "1등 8장"의 의미가 흔들린다.
 * - 뽑기는 지수 경주(exponential race): -ln(1-random())/응모권 이 가장 작은 쪽.
 *   응모권 수에 정확히 비례하는 확률이고, 중복 없이 여러 명 뽑을 때도 유지된다.
 * - 그 달에 한 번이라도 뽑힌 사람(만료·취소 포함)은 후보에서 빠진다.
 * - 51등 밖과 점수 0은 후보가 아니다.
 * - 같은 달에 두 번 불러도 이미 채워진 경품은 다시 뽑지 않는다.
 */
create or replace function public.run_monthly_draw(
  p_month_id text,
  p_note text default null
)
returns table (
  winner_id bigint,
  profile_id uuid,
  prize_name text,
  rank_at_draw integer,
  tickets_at_draw integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_round integer;
  v_draw_id bigint;
  v_candidates integer;
  v_total integer;
  v_prize record;
  v_pick record;
  v_winner_id bigint;
  v_deadline timestamptz;
begin
  /* 회신 기한: 추첨일 + 2일의 23:50 (KST).
     1일 00:00 추첨 → 3일 23:50, 4일 재추첨 → 6일 23:50.
     KST로 바꿔 날짜를 자른 뒤 다시 timestamptz로 되돌린다. */
  v_deadline := (
    date_trunc('day', now() at time zone 'Asia/Seoul')
    + interval '2 days' + interval '23 hours 50 minutes'
  ) at time zone 'Asia/Seoul';
  if p_month_id !~ '^[0-9]{6}$' then
    raise exception '잘못된 month_id입니다';
  end if;

  -- 아직 주인이 없는 경품만 대상이다. 이미 pending/confirmed면 건너뛴다.
  if not exists (
    select 1 from public.event_prizes p
    where p.enabled
      and not exists (
        select 1 from public.prize_winners w
        where w.month_id = p_month_id
          and w.prize_id = p.id
          and w.status in ('pending', 'confirmed')
      )
  ) then
    return;
  end if;

  select coalesce(max(d.round), 0) + 1 into v_round
  from public.prize_draws d where d.month_id = p_month_id;

  /* 그 달의 후보 풀을 임시 테이블에 고정한다.
     등수를 한 번만 매기기 위해서다. 경품마다 다시 계산하면 앞서 뽑힌 사람이
     빠지면서 등수가 밀려 올라가 응모권 수가 달라진다.

     ⚠️ 상태를 가리지 않고 그 달에 한 번이라도 뽑힌 사람은 전부 뺀다.
     expired(무응답)와 voided(취소)도 마찬가지다. 안 그러면 재추첨에서 다시 뽑혀
     unique (month_id, profile_id)에 걸려 추첨 전체가 실패한다.
     기한을 넘긴 사람에게 다시 기회를 주지 않는다는 정책과도 맞는다. */
  create temporary table if not exists draw_pool (
    profile_id uuid primary key,
    score integer not null,
    rank integer not null,
    tickets integer not null
  ) on commit drop;
  delete from draw_pool;

  insert into draw_pool (profile_id, score, rank, tickets)
  select r.profile_id, r.score, r.rank,
    case
      when r.rank = 1 then 8
      when r.rank = 2 then 5
      when r.rank = 3 then 3
      when r.rank between 4 and 10 then 2
      when r.rank between 11 and 50 then 1
      else 0
    end
  from (
    select
      ms.profile_id,
      ms.score,
      /* 랭킹 화면과 같은 순서여야 한다(get_monthly_ranking).
         마지막 profile_id는 동점·동시각일 때 순서를 고정하기 위한 것이다. */
      row_number() over (
        order by ms.score desc, ms.updated_at desc, ms.profile_id
      )::integer as rank
    from public.monthly_stats ms
    where ms.month_id = p_month_id and ms.score > 0
  ) r
  where not exists (
    select 1 from public.prize_winners w
    where w.month_id = p_month_id and w.profile_id = r.profile_id
  );

  delete from draw_pool where tickets = 0;

  select count(*)::integer, coalesce(sum(tickets), 0)::integer
  into v_candidates, v_total
  from draw_pool;

  if v_candidates = 0 then
    raise exception '추첨할 후보가 없습니다 (month_id=%)', p_month_id;
  end if;

  insert into public.prize_draws (month_id, candidate_count, total_tickets, round, note)
  values (p_month_id, v_candidates, v_total, v_round, p_note)
  returning id into v_draw_id;

  for v_prize in
    select p.id, p.name, p.sponsor
    from public.event_prizes p
    where p.enabled
      and not exists (
        select 1 from public.prize_winners w
        where w.month_id = p_month_id
          and w.prize_id = p.id
          and w.status in ('pending', 'confirmed')
      )
    order by p.sort_order, p.id
  loop
    /* 경품 하나마다 응모권 수에 비례해 한 명씩 뽑는다.
       random()은 [0,1)이라 0이 나올 수 있고 ln(0)은 오류다. 1-random()을 쓰면
       (0,1]이 되어 안전하다.
       뽑힌 사람은 풀에서 지워 다음 경품에 다시 나오지 않게 한다. */
    v_pick := null;
    select d.profile_id, d.score, d.rank, d.tickets
    into v_pick
    from draw_pool d
    order by -ln(1 - random()) / d.tickets
    limit 1;

    -- 후보가 경품 수보다 적으면 남은 경품은 다음 기회로 넘긴다.
    exit when v_pick is null;
    delete from draw_pool where draw_pool.profile_id = v_pick.profile_id;

    insert into public.prize_winners (
      draw_id, month_id, profile_id, prize_id, prize_name, prize_sponsor,
      score_at_draw, rank_at_draw, tickets_at_draw, total_tickets_at_draw, respond_by
    )
    values (
      v_draw_id, p_month_id, v_pick.profile_id, v_prize.id, v_prize.name, v_prize.sponsor,
      v_pick.score, v_pick.rank, v_pick.tickets, v_total, v_deadline
    )
    returning id into v_winner_id;

    /* OUT 파라미터에 직접 RETURNING 하지 않는다. profile_id·prize_name 등은
       컬럼 이름과 같아서 RETURNING 목록이 모호해진다. */
    winner_id := v_winner_id;
    profile_id := v_pick.profile_id;
    prize_name := v_prize.name;
    rank_at_draw := v_pick.rank;
    tickets_at_draw := v_pick.tickets;
    return next;
  end loop;
end;
$$;

/**
 * 3일이 지나도 주소를 안 넣은 당첨을 무효 처리하고 재추첨한다.
 * pg_cron으로 하루 한 번 돈다.
 */
create or replace function public.expire_stale_winners()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_expired integer;
  v_month text;
  v_months text[];
begin
  /* ⚠️ 이번 실행에서 만료된 달만 모은다.
     예전에는 status='expired'인 행 전체에서 달을 뽑았는데, 그러면 지난달·지지난달이
     매일 다시 추첨 대상이 됐다. 게다가 event_prizes는 "지금" 걸린 경품이라
     지난달을 현재 경품으로 다시 뽑는 것은 애초에 틀린 동작이다. */
  with expired as (
    update public.prize_winners
    set status = 'expired'
    where status = 'pending' and respond_by < now()
    returning month_id
  )
  select count(*), array_agg(distinct month_id) into v_expired, v_months from expired;

  if coalesce(v_expired, 0) = 0 then
    return 0;
  end if;

  -- 빈 자리가 생긴 달마다 재추첨한다.
  foreach v_month in array coalesce(v_months, array[]::text[])
  loop
    begin
      perform public.run_monthly_draw(v_month, '무응답 재추첨');
    exception when others then
      -- 후보가 없으면 넘어간다. 한 달이 실패해도 나머지는 처리해야 한다.
      raise notice '재추첨 실패 (month_id=%): %', v_month, sqlerrm;
    end;
  end loop;

  return v_expired;
end;
$$;

-- ---------------------------------------------------------------------------
-- 사용자용
-- ---------------------------------------------------------------------------

/** 내가 지금 응답해야 하는 당첨이 있는지. 화면 배너가 쓴다. */
create or replace function public.get_my_pending_prize()
returns table (
  winner_id bigint,
  month_id text,
  prize_name text,
  prize_sponsor text,
  respond_by timestamptz,
  status text,
  has_address boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    w.id,
    w.month_id,
    w.prize_name,
    w.prize_sponsor,
    w.respond_by,
    w.status,
    exists (select 1 from public.winner_addresses a where a.winner_id = w.id)
  from public.prize_winners w
  where w.profile_id = public.current_profile_id()
    and w.status in ('pending', 'confirmed')
    and w.respond_by > now() - interval '30 days'
  order by w.created_at desc
  limit 1
$$;

/** 당첨자가 배송지를 넣는다. 마감 전에만 받는다. */
create or replace function public.submit_winner_address(
  p_winner_id bigint,
  p_recipient text,
  p_phone text,
  p_postal_code text,
  p_address1 text,
  p_address2 text default null,
  p_memo text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
  v_winner public.prize_winners;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select public.current_profile_id() into v_profile_id;

  select * into v_winner from public.prize_winners where id = p_winner_id;
  if not found or v_winner.profile_id <> v_profile_id then
    -- 남의 당첨인지 없는 당첨인지 구분해주지 않는다.
    raise exception '해당 당첨 내역을 찾을 수 없습니다';
  end if;

  if v_winner.status = 'expired' then
    raise exception '입력 기간이 지났습니다';
  end if;
  if v_winner.status = 'voided' then
    raise exception '취소된 당첨입니다';
  end if;

  if btrim(coalesce(p_recipient, '')) = ''
     or btrim(coalesce(p_phone, '')) = ''
     or btrim(coalesce(p_postal_code, '')) = ''
     or btrim(coalesce(p_address1, '')) = ''
  then
    raise exception '받는 분, 연락처, 우편번호, 주소는 필수입니다';
  end if;

  insert into public.winner_addresses
    (winner_id, recipient, phone, postal_code, address1, address2, memo)
  values (
    p_winner_id, btrim(p_recipient), btrim(p_phone), btrim(p_postal_code),
    btrim(p_address1), nullif(btrim(coalesce(p_address2, '')), ''),
    nullif(btrim(coalesce(p_memo, '')), '')
  )
  on conflict (winner_id) do update set
    recipient = excluded.recipient,
    phone = excluded.phone,
    postal_code = excluded.postal_code,
    address1 = excluded.address1,
    address2 = excluded.address2,
    memo = excluded.memo;

  update public.prize_winners
  set status = 'confirmed', responded_at = now(), response_channel = 'site'
  where id = p_winner_id;
end;
$$;

/**
 * 관리자가 손으로 "주소 받았음"을 표시한다.
 *
 * 당첨자가 사이트를 쓰지 않고 **메일로 회신**하는 경우가 있다. 그때 사이트에서는
 * 영원히 pending으로 남아 만료·재추첨이 돌아버린다. 그것을 막는 장치다.
 * 주소 자체는 메일함에 있으므로 여기 저장하지 않는다. 메모만 남긴다.
 */
create or replace function public.mark_winner_responded(
  p_winner_id bigint,
  p_channel text default 'email',
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;
  if p_channel not in ('email', 'manual') then
    raise exception '경로는 email 또는 manual이어야 합니다';
  end if;

  update public.prize_winners
  set
    status = 'confirmed',
    responded_at = coalesce(responded_at, now()),
    response_channel = p_channel,
    response_note = nullif(btrim(coalesce(p_note, '')), '')
  where id = p_winner_id and status in ('pending', 'expired');

  if not found then
    raise exception '처리할 수 있는 당첨이 아닙니다';
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 관리자용
-- ---------------------------------------------------------------------------

create or replace function public.get_prize_winners(
  p_month_id text default null,
  p_limit integer default 100
)
returns table (
  winner_id bigint,
  month_id text,
  display_name text,
  email text,
  prize_name text,
  score_at_draw integer,
  rank_at_draw integer,
  tickets_at_draw integer,
  win_odds numeric,
  status text,
  respond_by timestamptz,
  notified_at timestamptz,
  response_channel text,
  response_note text,
  has_address boolean,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    w.id,
    w.month_id,
    coalesce(nullif(p.display_name, ''), '익명'),
    p.email::text,
    w.prize_name,
    w.score_at_draw,
    w.rank_at_draw,
    w.tickets_at_draw,
    -- 추첨 당시 이 사람의 응모권 비중. "왜 당첨됐나"에 답하는 값이다.
    case when w.total_tickets_at_draw > 0
      then round(w.tickets_at_draw::numeric * 100 / w.total_tickets_at_draw, 2)
      else 0 end,
    w.status,
    w.respond_by,
    w.notified_at,
    w.response_channel,
    w.response_note,
    exists (select 1 from public.winner_addresses a where a.winner_id = w.id),
    w.created_at
  from public.prize_winners w
  join public.profiles p on p.id = w.profile_id
  where public.is_admin()
    and (p_month_id is null or w.month_id = p_month_id)
  order by w.created_at desc
  limit least(greatest(coalesce(p_limit, 100), 1), 500)
$$;

/** 배송지 조회. 관리자만. 실제로 보낼 때만 열어본다. */
create or replace function public.get_winner_address(p_winner_id bigint)
returns table (
  recipient text, phone text, postal_code text,
  address1 text, address2 text, memo text
)
language sql
stable
security definer
set search_path = public
as $$
  select a.recipient, a.phone, a.postal_code, a.address1, a.address2, a.memo
  from public.winner_addresses a
  where public.is_admin() and a.winner_id = p_winner_id
$$;

/** 부정행위 등으로 당첨을 취소한다. 빈 자리는 다음 재추첨에서 채워진다. */
create or replace function public.void_prize_winner(p_winner_id bigint, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;
  if char_length(btrim(coalesce(p_reason, ''))) < 2 then
    raise exception '취소 사유를 남겨야 합니다';
  end if;

  update public.prize_winners
  set status = 'voided', voided_reason = btrim(p_reason)
  where id = p_winner_id and status in ('pending', 'confirmed');

  if not found then
    raise exception '취소할 수 있는 당첨이 아닙니다';
  end if;
end;
$$;

/** 배송이 끝난 주소를 파기한다. 개인정보를 필요 이상으로 들고 있지 않는다. */
create or replace function public.purge_delivered_addresses(p_days integer default 90)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer;
begin
  delete from public.winner_addresses a
  using public.prize_winners w
  where w.id = a.winner_id
    and w.status = 'confirmed'
    and w.responded_at < now() - make_interval(days => greatest(coalesce(p_days, 90), 7));

  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

-- ---------------------------------------------------------------------------
-- RLS / 권한
-- ---------------------------------------------------------------------------

alter table public.prize_draws enable row level security;
alter table public.prize_winners enable row level security;
alter table public.winner_addresses enable row level security;

-- 당첨 사실은 본인과 관리자만 본다. 남의 당첨을 훑을 수 있으면 안 된다.
drop policy if exists "prize_winners_own" on public.prize_winners;
create policy "prize_winners_own" on public.prize_winners
for select to authenticated
using (profile_id = public.current_profile_id() or public.is_admin());

drop policy if exists "prize_draws_admin" on public.prize_draws;
create policy "prize_draws_admin" on public.prize_draws
for select to authenticated using (public.is_admin());

-- 주소는 본인만. 관리자도 테이블 직접 조회가 아니라 함수를 거친다.
drop policy if exists "winner_addresses_own" on public.winner_addresses;
create policy "winner_addresses_own" on public.winner_addresses
for select to authenticated
using (
  exists (
    select 1 from public.prize_winners w
    where w.id = winner_addresses.winner_id
      and w.profile_id = public.current_profile_id()
  )
);

revoke all on public.prize_draws from anon, authenticated;
revoke all on public.prize_winners from anon, authenticated;
revoke all on public.winner_addresses from anon, authenticated;
grant select on public.prize_draws to authenticated;
grant select on public.prize_winners to authenticated;
grant select on public.winner_addresses to authenticated;

-- 추첨·만료·파기는 서버(cron)만 부른다. 클라이언트에 열지 않는다.
revoke all on function public.run_monthly_draw(text, text) from public, anon, authenticated;
revoke all on function public.expire_stale_winners() from public, anon, authenticated;
revoke all on function public.purge_delivered_addresses(integer) from public, anon, authenticated;

revoke all on function public.get_my_pending_prize() from public, anon;
revoke all on function public.submit_winner_address(bigint, text, text, text, text, text, text)
  from public, anon;
revoke all on function public.get_prize_winners(text, integer) from public, anon;
revoke all on function public.get_winner_address(bigint) from public, anon;
revoke all on function public.void_prize_winner(bigint, text) from public, anon;
revoke all on function public.mark_winner_responded(bigint, text, text) from public, anon;

grant execute on function public.get_my_pending_prize() to authenticated;
grant execute on function public.submit_winner_address(bigint, text, text, text, text, text, text)
  to authenticated;
grant execute on function public.get_prize_winners(text, integer) to authenticated;
grant execute on function public.get_winner_address(bigint) to authenticated;
grant execute on function public.void_prize_winner(bigint, text) to authenticated;
grant execute on function public.mark_winner_responded(bigint, text, text) to authenticated;

notify pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- 스케줄 등록 (pg_cron 확장을 켠 뒤 한 번만 실행)
-- ---------------------------------------------------------------------------
--
--   create extension if not exists pg_cron;
--
--   -- 매월 1일 00:00 KST = 전날 15:00 UTC
--   select cron.schedule('prize-draw', '0 15 * * *', $$
--     select public.run_monthly_draw(
--       to_char((now() at time zone 'Asia/Seoul') - interval '1 day', 'YYYYMM')
--     )
--     where to_char(now() at time zone 'Asia/Seoul', 'DD') = '01'
--   $$);
--
--   -- 무응답 만료 + 재추첨: 매일 00:00 KST (3일 23:50 마감 직후 = 4일 00:00 재추첨)
--   select cron.schedule('prize-expire', '0 15 * * *', $$select public.expire_stale_winners()$$);
--
--   -- 배송 완료 주소 파기: 매주 일요일 03:00 KST
--   select cron.schedule('prize-purge', '0 18 * * 0', $$select public.purge_delivered_addresses(90)$$);
--
-- ⚠️ cron.schedule의 시간은 UTC다. KST는 +9시간이라 00:00 KST = 15:00 UTC(전날)다.
--    추첨 잡은 매일 돌지만 안쪽의 where가 1일에만 통과시킨다. pg_cron에는
--    "매월 1일"을 KST로 표현할 방법이 없어서(크론은 UTC 기준 날짜를 본다)
--    이렇게 날짜 판정을 SQL로 옮겼다.
