-- Expand every local typing pool with original, practice-friendly content.
-- Safe to rerun: 0017 enforces uniqueness by language, mode, and trimmed text.

insert into public.sentences (language, mode, text, is_meme, enabled)
select 'kor', 'short', value, false, true
from unnest(array[
  '오늘의 집중이 내일의 여유를 만든다.',
  '천천히 가도 방향이 맞으면 충분하다.',
  '작은 습관은 생각보다 멀리 데려간다.',
  '좋은 질문은 새로운 길을 열어 준다.',
  '마음의 속도는 사람마다 다를 수 있다.',
  '한 번의 친절이 하루를 환하게 바꾼다.',
  '준비된 사람은 기회를 오래 붙잡는다.',
  '쉬어 가는 시간도 과정의 일부이다.',
  '선명한 목표는 망설임을 줄여 준다.',
  '꾸준함은 재능이 머무를 자리를 만든다.',
  '익숙함 속에서도 새로움을 발견할 수 있다.',
  '오늘 배운 것은 내일의 도구가 된다.',
  '진심은 서두르지 않아도 전해진다.',
  '실수는 다음 선택을 더 단단하게 만든다.',
  '좋은 리듬은 오래 집중하게 해 준다.',
  '기록하면 막연했던 생각이 또렷해진다.',
  '조용한 용기도 세상을 움직일 수 있다.',
  '한 걸음씩 가면 먼 길도 가까워진다.',
  '서로의 다름은 새로운 가능성이 된다.',
  '충분히 듣는 것이 대화의 시작이다.',
  '오늘의 노력은 사라지지 않고 쌓인다.',
  '마음을 정리하면 해야 할 일이 보인다.',
  '작은 변화가 큰 흐름을 바꾸기도 한다.',
  '좋은 선택은 자신을 믿는 데서 시작된다.',
  '어려운 순간에도 배울 것은 남아 있다.',
  '정확한 한 걸음이 빠른 열 걸음보다 낫다.',
  '기다림은 때로 가장 적극적인 선택이다.',
  '나다운 속도로 가는 것도 용기이다.',
  '반복한 만큼 손끝은 더 정확해진다.',
  '따뜻한 말은 오래 기억되는 힘이 있다.',
  '몰입은 평범한 시간을 특별하게 만든다.',
  '시작한 사람만이 다음 장면을 만난다.',
  '균형은 멈춤과 움직임 사이에서 생긴다.',
  '문제를 나누면 해결의 순서가 보인다.',
  '하루의 끝에는 작은 성취를 돌아보자.',
  '좋은 생각은 적어 둘 때 더 오래 남는다.',
  '배려는 상대의 시간을 존중하는 태도이다.',
  '익숙하지 않은 길에서 시야가 넓어진다.',
  '지금 할 수 있는 일부터 차분히 시작하자.',
  '완벽보다 완성이 다음 기회를 만든다.',
  '마음이 복잡할수록 호흡을 천천히 하자.',
  '작은 약속을 지키며 신뢰를 쌓아 간다.',
  '좋은 하루는 사소한 선택에서 시작된다.',
  '어제보다 나은 오늘이면 충분한 진전이다.',
  '집중한 시간은 결과보다 먼저 나를 바꾼다.',
  '낯선 의견에도 배울 만한 이유가 있다.',
  '한계는 시도할 때마다 조금씩 이동한다.',
  '정돈된 공간은 생각에도 여백을 준다.',
  '서두르지 않아도 꾸준하면 앞으로 간다.',
  '끝까지 읽는 습관이 깊은 이해를 만든다.'
]) as item(value)
on conflict do nothing;

insert into public.sentences (language, mode, text, is_meme, enabled)
select 'kor', 'long', value, false, true
from unnest(array[
  '아침에 해야 할 일을 세 가지로 정리하면 하루가 훨씬 단순해진다. 모든 일을 한꺼번에 해결하려 하기보다 중요한 일부터 차례로 끝내는 편이 집중력을 오래 유지하는 데 도움이 된다.',
  '새로운 기술을 배울 때 처음부터 빠르게 하려는 마음은 오히려 실수를 늘린다. 정확한 동작을 천천히 반복하고 익숙해진 뒤 속도를 높이면 배운 내용이 더 오래 남고 자신감도 자연스럽게 따라온다.',
  '좋은 대화는 말을 많이 하는 데서 시작되지 않는다. 상대가 무엇을 중요하게 생각하는지 끝까지 듣고, 이해한 내용을 차분히 확인할 때 서로 다른 생각 사이에도 안전한 다리가 놓인다.',
  '계획은 미래를 완벽하게 예측하기 위한 문서가 아니다. 지금 알고 있는 정보로 다음 행동을 정하고, 상황이 달라졌을 때 주저 없이 고쳐 나가기 위한 지도에 더 가깝다.',
  '오래 집중하려면 의지만 믿기보다 환경을 먼저 정리하는 것이 좋다. 알림을 끄고 필요한 자료만 펼쳐 두면 사소한 선택에 쓰이는 에너지가 줄어들어 중요한 일에 더 깊이 몰입할 수 있다.',
  '하루 동안 있었던 일을 짧게 기록하면 기억 속에서 뒤섞이던 감정과 사실이 분리된다. 무엇이 어려웠고 무엇이 도움이 되었는지 적다 보면 다음에는 더 나은 선택을 할 근거가 생긴다.',
  '익숙한 방법이 언제나 가장 좋은 방법은 아니다. 가끔은 하던 일을 멈추고 과정 전체를 바라보아야 불필요한 반복을 발견하고 더 단순한 해결책을 선택할 수 있다.',
  '실수를 숨기면 같은 문제가 조용히 반복되지만 실수를 공유하면 팀 전체가 배울 수 있다. 잘못의 책임을 분명히 하되 사람을 탓하기보다 원인과 재발 방지에 집중하는 태도가 중요하다.',
  '몸과 마음이 지쳤을 때의 휴식은 게으름이 아니라 회복을 위한 작업이다. 충분히 쉬고 돌아온 사람은 같은 시간에도 더 정확하게 판단하고 주변 사람에게도 여유 있게 반응할 수 있다.',
  '큰 목표는 방향을 알려 주지만 실제 변화를 만드는 것은 매일의 작은 행동이다. 부담 없이 반복할 수 있는 최소 단위를 정해 두면 의욕이 낮은 날에도 흐름을 잃지 않을 수 있다.',
  '새로운 장소를 걷다 보면 평소에는 지나치던 소리와 표정이 눈에 들어온다. 익숙함에서 잠시 벗어나는 경험은 생각의 굳은 부분을 풀어 주고 예상하지 못한 아이디어를 데려온다.',
  '문제를 해결하기 전에 무엇이 진짜 문제인지 한 문장으로 적어 보는 것이 좋다. 질문이 선명해지면 필요한 정보와 불필요한 걱정이 구분되고 해결의 첫 단계도 자연스럽게 보인다.',
  '친절은 거창한 행동보다 상대의 작은 불편을 먼저 알아차리는 데서 드러난다. 문을 잠시 잡아 주거나 대답을 재촉하지 않는 태도는 짧은 순간에도 깊은 존중을 전달한다.',
  '배운 내용을 누군가에게 설명해 보면 이해한 부분과 외운 부분이 분명히 나뉜다. 막히는 대목을 다시 찾아보고 자신의 말로 정리하는 과정에서 지식은 비로소 사용할 수 있는 도구가 된다.',
  '속도가 느리다고 해서 성장이 멈춘 것은 아니다. 눈에 띄지 않는 시간에도 경험은 쌓이고 있으며, 어느 순간 이전에는 어려웠던 일이 자연스러워지는 때가 찾아온다.',
  '서로 다른 의견이 나왔을 때 곧바로 결론을 내리기보다 각자가 중요하게 보는 기준을 먼저 확인해야 한다. 기준을 공유하면 대립처럼 보이던 문제에서도 함께 선택할 수 있는 지점이 생긴다.',
  '정리되지 않은 생각은 머릿속에서 실제보다 더 크게 느껴진다. 종이에 적고 지금 바꿀 수 있는 것과 기다려야 하는 것을 나누면 불안은 줄고 행동은 구체적으로 바뀐다.',
  '완벽한 시작을 기다리다 보면 좋은 기회도 지나갈 수 있다. 작게 시험하고 결과를 살핀 뒤 다음 단계를 조정하는 방식은 실패의 부담을 줄이면서도 꾸준한 진전을 만든다.',
  '신뢰는 특별한 순간보다 평범한 약속을 반복해서 지킬 때 만들어진다. 늦을 것 같으면 미리 알리고, 모르는 것은 솔직히 말하는 태도가 관계를 오래 건강하게 유지한다.',
  '집중력이 흐려질 때 억지로 자리에 붙어 있기보다 잠시 일어나 몸을 움직여 보자. 짧은 산책과 깊은 호흡만으로도 시선이 환기되고 복잡했던 문제를 새롭게 바라볼 수 있다.',
  '좋은 글은 어려운 단어보다 정확한 관찰에서 나온다. 무엇을 보았고 어떻게 느꼈는지 구체적으로 적으면 짧은 문장도 독자에게 선명한 장면과 오래 남는 감정을 전할 수 있다.',
  '시간을 잘 쓴다는 것은 모든 순간을 일로 채우는 뜻이 아니다. 중요한 일에 충분히 집중하고 사람과 휴식에도 자리를 내어 줄 때 하루 전체의 만족도와 지속 가능성이 높아진다.',
  '낯선 일을 맡았을 때는 전체를 한 번에 이해하려 하지 않아도 된다. 먼저 결과물의 모양을 살피고 필요한 단계를 작게 나누면 모호했던 일도 실행 가능한 과제로 바뀐다.',
  '피드백을 받을 때 마음이 불편한 것은 자연스러운 일이다. 바로 방어하기보다 도움이 되는 사실을 골라 작은 변화로 시험해 보면 타인의 시선이 성장의 재료가 될 수 있다.',
  '반복되는 일상에도 자세히 보면 매일 다른 장면이 있다. 하늘의 빛과 거리의 냄새, 사람들의 목소리에 잠시 주의를 기울이면 평범한 하루가 풍부한 기억으로 남는다.',
  '결정을 미루는 이유가 정보 부족인지 실패에 대한 두려움인지 구분해야 한다. 필요한 정보가 충분하다면 작은 위험을 받아들이고 선택하는 편이 오래 망설이는 것보다 많은 것을 가르쳐 준다.',
  '함께 일할 때 진행 상황을 자주 공유하면 작은 오해가 큰 문제로 자라는 것을 막을 수 있다. 완성된 결과만 보여 주기보다 현재의 판단과 어려움을 알리는 것이 협업을 더 단단하게 만든다.',
  '자신에게 건네는 말도 다른 사람에게 하는 말만큼 중요하다. 실수한 순간에 모욕적인 표현 대신 다음에 바꿀 행동을 구체적으로 말하면 회복이 빨라지고 도전할 힘도 남는다.',
  '매일 같은 시간에 짧게 연습하면 시작을 고민하는 시간이 줄어든다. 행동이 일정한 리듬을 갖게 되면 의욕에 크게 기대지 않고도 실력을 안정적으로 쌓아 갈 수 있다.',
  '좋은 질문은 정답을 확인하는 데서 끝나지 않고 생각의 범위를 넓힌다. 왜 그런지, 다른 조건에서는 어떻게 달라지는지 묻는 습관은 익숙한 지식에서도 새로운 연결을 발견하게 한다.',
  '책을 빠르게 많이 읽는 것보다 한 문장을 오래 생각하는 시간이 더 값질 때가 있다. 마음에 남은 대목을 자신의 경험과 연결하면 읽은 내용은 단순한 정보에서 삶의 기준으로 바뀐다.',
  '갈등이 생겼을 때 상대의 의도를 추측하기보다 실제로 일어난 행동과 그 영향을 말하는 편이 좋다. 사실을 중심으로 대화하면 감정은 존중하면서도 해결해야 할 문제를 놓치지 않는다.',
  '작업을 마친 뒤 짧게 점검하는 습관은 다음 작업의 속도를 높인다. 잘된 점과 막힌 이유, 다시 쓸 수 있는 방법을 남겨 두면 경험이 사라지지 않고 조직의 자산으로 쌓인다.',
  '목표를 이루는 과정에는 눈에 보이는 성과가 없는 구간도 있다. 그 시간을 실패로 판단하지 않고 기본기를 다지는 시기로 받아들이면 흔들리지 않고 다음 단계까지 나아갈 수 있다.',
  '사과는 자신의 의도를 설명하는 일보다 상대가 겪은 영향을 인정하는 일에 가깝다. 변명 없이 잘못을 말하고 구체적인 개선 행동을 약속할 때 관계는 다시 신뢰를 쌓을 기회를 얻는다.',
  '집 안의 작은 공간 하나를 정리하면 마음에도 움직일 자리가 생긴다. 필요 없는 것을 덜어 내고 자주 쓰는 물건의 자리를 정하면 매일 반복되는 불편과 피로가 눈에 띄게 줄어든다.',
  '새로운 습관은 거창한 결심보다 기존 일상에 자연스럽게 연결할 때 오래간다. 아침 물 한 잔 뒤에 스트레칭을 하는 것처럼 분명한 신호를 정하면 시작이 훨씬 쉬워진다.',
  '우리는 종종 결과만 비교하며 다른 사람의 긴 과정을 잊는다. 자신의 출발점과 어제의 모습을 기준으로 바라보면 조급함을 줄이고 지금 필요한 연습에 더 솔직하게 집중할 수 있다.',
  '여유가 없을수록 모든 요청에 즉시 답하려는 습관을 돌아볼 필요가 있다. 중요한 일의 순서를 설명하고 가능한 시간을 분명히 말하는 것은 거절이 아니라 책임 있는 약속이다.',
  '좋은 도구는 일을 대신해 주기보다 생각을 더 명확하게 표현하도록 돕는다. 기능을 많이 아는 것보다 필요한 순간에 알맞은 기능을 선택하고 결과를 검토하는 능력이 더 중요하다.',
  '불확실한 상황에서는 하나의 예상에 모든 계획을 걸지 않는 편이 안전하다. 가능한 경우를 몇 가지로 나누고 각 상황의 첫 행동을 준비하면 변화가 와도 침착하게 대응할 수 있다.',
  '누군가의 성장을 돕고 싶다면 정답을 바로 알려 주기보다 스스로 발견할 시간을 주어야 한다. 적절한 질문과 기다림은 상대가 자신의 판단을 믿고 다음 문제도 해결하게 만든다.',
  '감정이 크게 흔들릴 때 중요한 결정을 바로 내리지 않는 것도 지혜이다. 몸을 쉬게 하고 사실을 다시 확인한 뒤 선택하면 순간의 분노나 두려움이 미래를 대신 결정하는 일을 줄일 수 있다.',
  '작은 성공을 충분히 인정하면 다음 도전을 위한 에너지가 생긴다. 아직 부족한 점만 바라보기보다 이미 해낸 과정과 도움을 준 사람을 돌아보는 태도가 긴 여정을 지탱한다.',
  '회의를 시작하기 전에 목적과 끝낼 시간을 분명히 하면 대화가 훨씬 선명해진다. 결정할 일과 공유할 일을 구분하고 마지막에 담당과 기한을 확인하면 같은 회의를 반복하지 않아도 된다.',
  '정보가 많을수록 무엇을 믿을지 판단하는 능력이 중요해진다. 출처와 작성 시점을 확인하고 여러 자료가 같은 사실을 말하는지 비교하는 습관이 성급한 결론을 막아 준다.',
  '창의적인 생각은 아무 제약도 없을 때보다 적당한 조건 안에서 잘 나오기도 한다. 시간과 목적, 사용할 수 있는 자원을 정해 두면 막연한 상상이 실제로 시험할 수 있는 아이디어가 된다.',
  '사람은 누구나 집중이 잘되는 시간대가 다르다. 자신의 리듬을 관찰해 어려운 일은 에너지가 높은 시간에 두고 단순한 일은 낮은 시간에 배치하면 같은 하루를 더 편안하게 쓸 수 있다.',
  '경험이 쌓일수록 모르는 것을 인정하는 태도가 더 중요해진다. 익숙한 답을 잠시 내려놓고 새로운 사실을 확인할 때 오래된 지식도 현재에 맞는 판단으로 다시 살아난다.',
  '길을 잃었다고 느껴질 때는 멀리 있는 목표보다 지금 서 있는 위치를 확인해야 한다. 가진 자원과 필요한 도움을 적어 보면 막막함 속에서도 오늘 움직일 수 있는 방향이 보인다.'
]) as item(value)
on conflict do nothing;

insert into public.sentences (language, mode, text, is_meme, enabled)
select 'kor', 'word', value, false, true
from unnest(array[
  '가로등', '간격', '갈림길', '감각', '강변', '개울', '건반', '결심', '경험', '징검다리',
  '고요', '공감', '과정', '관찰', '구름빛', '기록', '기준', '기회', '깊이', '나침반',
  '낙엽', '노을', '눈길', '다짐', '단서', '대화', '도전', '윤슬', '리듬', '마중',
  '메아리', '모험', '물결', '바람결', '발견', '방향', '배려', '변화', '별빛', '보람',
  '산책', '상상', '새벽빛', '선택', '성장', '소나기', '속도', '쉼표', '시선', '책갈피'
]) as item(value)
on conflict do nothing;

insert into public.sentences (language, mode, text, is_meme, enabled)
select 'eng', 'short', value, false, true
from unnest(array[
  'A clear plan makes a busy day feel lighter.',
  'Small steps can carry us across a long distance.',
  'Good questions often reveal better directions.',
  'Quiet effort grows stronger through repetition.',
  'A kind word can change the rhythm of a day.',
  'Careful listening is the beginning of trust.',
  'Progress matters more than a perfect beginning.',
  'A short pause can restore a tired mind.',
  'Practice turns difficult motions into natural ones.',
  'Clear spaces often invite clearer thoughts.',
  'Every useful habit begins with one simple action.',
  'Patience gives good ideas time to become stronger.',
  'Writing things down makes vague thoughts visible.',
  'The right pace is the one you can sustain.',
  'Honest feedback can become a map for growth.',
  'A calm response creates room for better choices.',
  'Curiosity keeps familiar places from feeling empty.',
  'Rest is part of the work, not its opposite.',
  'One finished task is worth many delayed intentions.',
  'Shared goals make different opinions easier to hear.',
  'A steady routine protects attention from distraction.',
  'Simple words can carry deep and lasting meaning.',
  'Confidence grows when small promises are kept.',
  'New paths appear when old assumptions are questioned.',
  'A thoughtful pause can prevent a careless answer.',
  'Today is a good place to begin again.',
  'Useful knowledge becomes stronger when it is shared.',
  'A gentle pace can still produce remarkable progress.',
  'Clear boundaries make reliable promises possible.',
  'Every mistake contains information for the next attempt.',
  'Focused minutes often matter more than busy hours.',
  'A different view can turn a wall into a doorway.',
  'Consistent practice gives talent somewhere to grow.',
  'The best tools make difficult ideas easier to express.',
  'A well-defined problem is already partly solved.',
  'Gratitude helps ordinary moments remain memorable.',
  'Courage sometimes looks like asking for help.',
  'Careful work creates speed that lasts.',
  'A flexible plan can survive an unexpected change.',
  'Strong teams make uncertainty safe to discuss.',
  'A fresh morning offers another chance to improve.',
  'Deep understanding takes longer than quick recognition.',
  'Respect is often shown through small acts of attention.',
  'A useful note can save hours of repeated work.',
  'Balanced days leave space for effort and recovery.',
  'The next step becomes clearer after the first one.',
  'Good decisions begin with accurate information.',
  'An open mind notices options that fear overlooks.',
  'Meaningful change is usually built in quiet moments.',
  'Finishing creates lessons that planning alone cannot give.'
]) as item(value)
on conflict do nothing;

insert into public.sentences (language, mode, text, is_meme, enabled)
select 'eng', 'long', value, false, true
from unnest(array[
  'When a task feels too large to begin, write down the smallest useful action you can complete in ten minutes. A clear first move reduces uncertainty and often creates enough momentum for the next one.',
  'A productive morning does not require a complicated routine. A few quiet minutes, a short list of priorities, and a protected block of attention can shape the rest of the day with surprising strength.',
  'Learning becomes more durable when you explain an idea in your own words. The places where your explanation becomes vague reveal exactly what you need to review, test, or understand more deeply.',
  'Good collaboration depends on sharing unfinished thoughts as well as polished results. Early questions and small updates allow a team to correct its direction before time and effort harden around the wrong plan.',
  'Rest is not time stolen from meaningful work. A rested mind notices details, weighs choices more carefully, and returns to difficult problems with patience that cannot be produced by effort alone.',
  'A thoughtful conversation begins with the belief that another person may see something you have missed. Listening for the reasons beneath an opinion turns disagreement into a chance to improve the decision.',
  'Plans are most useful when they remain easy to change. They should identify the next action and the reason behind it, while leaving enough flexibility to respond when new information changes the situation.',
  'Small habits survive because they fit inside ordinary life. Connecting a new action to something you already do each day removes the need to decide when to begin and makes repetition feel natural.',
  'Mistakes become valuable only after they are examined without fear or blame. Asking what happened, what signal was missed, and what could be changed next time converts discomfort into practical knowledge.',
  'A clear boundary is not a rejection of other people. It is an honest description of what you can promise, which protects your attention and helps others make plans based on reliable information.',
  'When information arrives faster than you can process it, pause before forming a conclusion. Check the source, the date, and the surrounding context, then compare the claim with another trustworthy account.',
  'Creative ideas often appear after the obvious answers have been written down. Staying with a question a little longer gives the mind time to connect distant experiences and discover a less familiar path.',
  'The quality of a meeting improves when everyone knows what must be decided. A clear purpose, a short time limit, and named next steps turn conversation into coordinated action instead of repeated discussion.',
  'Confidence is built through evidence rather than wishes. Each small promise you keep gives your mind another reason to trust that you can begin, adapt, and finish work even when motivation changes.',
  'A difficult emotion becomes easier to understand when it is described precisely. Naming what happened, what you expected, and what you need separates the present problem from the stories surrounding it.',
  'Reading slowly can be more useful than finishing quickly. A single paragraph connected to your own experience may change how you think and act long after the rest of the book has faded from memory.',
  'Progress is not always visible while it is happening. Repeated practice quietly improves timing, judgment, and endurance until a task that once demanded full attention begins to feel steady and familiar.',
  'Before solving a problem, try to describe it in one accurate sentence. A precise question reveals which facts matter, which assumptions need testing, and which worries do not belong to the problem at all.',
  'Respect often appears in the way we handle another person’s time. Arriving prepared, answering honestly, and warning someone early about a delay are small actions that make cooperation feel safe.',
  'An unfamiliar assignment becomes manageable when you first study the shape of a good result. Once the destination is visible, you can divide the work into smaller decisions and request help with precision.',
  'Comparison becomes harmful when it ignores different starting points and hidden effort. Measuring your progress against your earlier work keeps attention on the practice that is actually within your control.',
  'A useful review at the end of a project does not need to be long. Record what worked, what slowed the team down, and what should be reused so that experience remains available for the next challenge.',
  'When focus begins to fade, forcing another hour may produce less than a brief walk. Movement, water, and a change of view can reset attention and return you to the same problem with a quieter mind.',
  'Reliable systems reduce the number of decisions that depend on memory. Checklists, clear names, and simple routines protect important work from interruption while leaving more attention for judgment.',
  'An apology becomes meaningful when it recognizes impact before explaining intent. Naming the harm, accepting responsibility, and changing a specific behavior creates a real foundation for rebuilding trust.',
  'The fastest solution is not always the one completed first. Work that is checked, documented, and easy for another person to understand continues creating value after the original task has ended.',
  'A new perspective often begins with a change in environment. Walking a different street or working in another room can interrupt familiar patterns and make space for details you had stopped noticing.',
  'When several priorities compete, decide what must remain true by the end of the day. This single standard makes tradeoffs clearer and prevents urgent but unimportant requests from controlling every hour.',
  'Helpful feedback describes an observable action and its effect. It avoids guessing about character, offers a possible improvement, and leaves the other person with something concrete to try.',
  'Uncertainty feels smaller when you prepare for more than one outcome. Naming a few likely scenarios and the first response to each one creates calm without pretending that the future is predictable.',
  'A good tool should reduce friction without hiding responsibility. Automation can handle repeated steps, but a person must still understand the goal, inspect the result, and decide whether it makes sense.',
  'Long projects need signs of progress before the final result appears. Visible milestones help people adjust their effort, celebrate useful movement, and notice problems while they are still inexpensive to fix.',
  'You do not need to answer every request immediately. A brief acknowledgment and a realistic time for response often serve others better than a rushed promise that cannot be kept.',
  'Careful observation is the foundation of clear writing. Specific sounds, movements, and textures give the reader a scene to enter, while broad descriptions leave even strong emotions without a place to land.',
  'The best time for demanding work differs from person to person. Watching your energy for a week can reveal when to schedule deep thinking and when to reserve simpler tasks that require less attention.',
  'People learn more readily when questions are safe to ask. A leader who admits uncertainty and responds without ridicule creates a team that finds problems early instead of hiding them until they grow.',
  'A crowded schedule may be a sign that choices have not been made. Removing one low-value commitment can create more progress than squeezing another task into a day that already has no room.',
  'Consistency does not mean doing the same amount every day. It means keeping a relationship with the work, sometimes through a full session and sometimes through one small action that preserves the rhythm.',
  'When conflict grows, separate the facts from the interpretation. Describing what occurred and asking how it affected each person makes it easier to address the issue without attacking identity.',
  'A short written record can prevent the same decision from being debated again. Capture the choice, the evidence available at the time, and the conditions that would justify changing it later.',
  'Curiosity is a practical skill, not merely a personality trait. Asking what else could be true and what evidence would change your mind protects judgment from becoming trapped by the first explanation.',
  'Finishing a small version teaches more than endlessly improving a private draft. Real use reveals which details matter, which assumptions were wrong, and where the next round of effort will have the most value.',
  'Gratitude becomes more powerful when it is specific. Telling someone exactly what they did and how it helped turns a polite phrase into useful recognition that can guide future cooperation.',
  'Difficult choices rarely become easy through more thinking alone. After gathering enough information, choose a reasonable path, define a point for review, and allow experience to provide the missing evidence.',
  'A calm workspace cannot remove every distraction, but it can reduce unnecessary ones. Keeping only the needed materials visible makes returning to the task easier after an interruption.',
  'Teaching someone else requires patience with a different pace of understanding. Clear examples, time to practice, and questions that reveal reasoning build independence more effectively than repeated instructions.',
  'The desire for a perfect result can hide a fear of being evaluated. Setting a clear definition of done and sharing work at agreed stages keeps quality high without allowing anxiety to delay every decision.',
  'Some problems need persistence, while others need distance. Recognizing when to continue and when to pause is a form of judgment developed by noticing how the quality of your attention changes.',
  'Strong relationships are maintained through ordinary reliability. Remembering a concern, following up after a difficult day, and keeping small commitments show care more convincingly than occasional grand gestures.',
  'At the end of a demanding day, notice one thing you completed and one thing you learned. This simple review protects progress from being erased by the unfinished work that naturally remains.'
]) as item(value)
on conflict do nothing;

insert into public.sentences (language, mode, text, is_meme, enabled)
select 'eng', 'word', value, false, true
from unnest(array[
  'adapt', 'anchor', 'waypoint', 'breeze', 'canvas', 'clarity', 'compass', 'courage', 'curiosity', 'attentive',
  'cooperate', 'craftsmanship', 'empathy', 'mindful', 'trailhead', 'glimpse', 'resilient', 'harbor', 'horizon', 'insight',
  'daybreak', 'kindness', 'lantern', 'iterate', 'meadow', 'momentum', 'notebook', 'observe', 'patience', 'pathway',
  'practice', 'progress', 'purpose', 'question', 'reflection', 'rhythm', 'signal', 'spark', 'steady', 'sunrise',
  'support', 'thoughtful', 'timing', 'trust', 'understand', 'useful', 'wander', 'welcome', 'wisdom', 'wonder'
]) as item(value)
on conflict do nothing;

notify pgrst, 'reload schema';
