-- User management helpers and display-name audit history.

create table if not exists public.profile_display_name_history (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  changed_by_profile_id uuid references public.profiles(id) on delete set null,
  old_display_name text,
  new_display_name text not null,
  source text not null default 'user',
  reason text,
  changed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.profile_display_name_history
  drop constraint if exists profile_display_name_history_source_check;

alter table public.profile_display_name_history
  add constraint profile_display_name_history_source_check
  check (source in ('user', 'admin', 'backfill'));

create index if not exists profile_display_name_history_profile_changed_idx
  on public.profile_display_name_history (profile_id, changed_at desc);

create index if not exists profile_display_name_history_changed_idx
  on public.profile_display_name_history (changed_at desc);

alter table public.profile_display_name_history enable row level security;

drop policy if exists "profile_display_name_history_admin_select"
  on public.profile_display_name_history;

create policy "profile_display_name_history_admin_select"
on public.profile_display_name_history
for select
to authenticated
using (public.is_admin());

revoke all on public.profile_display_name_history from public, anon, authenticated;
grant select on public.profile_display_name_history to authenticated;

insert into public.profile_display_name_history (
  profile_id,
  changed_by_profile_id,
  old_display_name,
  new_display_name,
  source,
  reason,
  changed_at
)
select
  p.id,
  null,
  null,
  p.display_name,
  'backfill',
  '변경 이력 도입 전 기록입니다. 이전 닉네임은 저장되어 있지 않습니다.',
  p.display_name_changed_at
from public.profiles p
where p.display_name_changed_at is not null
  and nullif(p.display_name, '') is not null
  and not exists (
    select 1
    from public.profile_display_name_history h
    where h.profile_id = p.id
      and h.changed_at = p.display_name_changed_at
      and h.new_display_name = p.display_name
  );

create or replace function public.update_my_display_name(p_display_name text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cooldown constant interval := interval '24 hours';
  v_profile_id uuid;
  v_current text;
  v_nickname_set boolean;
  v_changed_at timestamptz;
  v_available timestamptz;
  v_left interval;
  v_name text := btrim(coalesce(p_display_name, ''));
  v_now timestamptz := now();
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if char_length(v_name) < 1 or char_length(v_name) > 12 then
    raise exception '닉네임은 1~12자여야 합니다';
  end if;

  if v_name ~ ('[' || chr(8203) || chr(8204) || chr(8205) || chr(8206) || chr(8207)
                   || chr(160) || chr(65279) || ']')
     or v_name ~ '[[:cntrl:]]'
  then
    raise exception '사용할 수 없는 문자가 있습니다';
  end if;

  select public.current_profile_id() into v_profile_id;
  if v_profile_id is null then
    raise exception 'Profile not found';
  end if;

  select display_name, nickname_set, display_name_changed_at
  into v_current, v_nickname_set, v_changed_at
  from public.profiles
  where id = v_profile_id
  for update;

  if v_current is not null and v_current = v_name then
    return v_current;
  end if;

  if coalesce(v_nickname_set, false) and v_changed_at is not null then
    v_available := v_changed_at + v_cooldown;
    if v_now < v_available then
      v_left := v_available - v_now;
      raise exception '닉네임은 24시간에 한 번만 바꿀 수 있습니다. %시간 %분 뒤에 다시 시도해 주세요',
        floor(extract(epoch from v_left) / 3600)::int,
        (floor(extract(epoch from v_left) / 60)::int % 60);
    end if;
  end if;

  if exists (
    select 1 from public.profiles
    where display_name_lower = lower(v_name) and id <> v_profile_id
  ) then
    raise exception '이미 사용 중인 닉네임입니다';
  end if;

  begin
    update public.profiles
    set display_name = v_name,
        display_name_lower = lower(v_name),
        nickname_set = true,
        display_name_changed_at = v_now
    where id = v_profile_id;
  exception
    when unique_violation then
      raise exception '이미 사용 중인 닉네임입니다';
  end;

  update public.monthly_stats
  set nickname = v_name
  where profile_id = v_profile_id
    and month_id = to_char(v_now at time zone 'Asia/Seoul', 'YYYYMM');

  insert into public.profile_display_name_history (
    profile_id,
    changed_by_profile_id,
    old_display_name,
    new_display_name,
    source,
    changed_at
  )
  values (
    v_profile_id,
    v_profile_id,
    nullif(v_current, ''),
    v_name,
    'user',
    v_now
  );

  return v_name;
end;
$$;

create or replace function public.admin_update_user_display_name(
  p_profile_id uuid,
  p_display_name text,
  p_reason text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid;
  v_current text;
  v_name text := btrim(coalesce(p_display_name, ''));
  v_reason text := nullif(btrim(coalesce(p_reason, '')), '');
  v_now timestamptz := now();
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;

  if p_profile_id is null then
    raise exception 'Profile is required';
  end if;

  if char_length(v_name) < 1 or char_length(v_name) > 12 then
    raise exception '닉네임은 1~12자여야 합니다';
  end if;

  if char_length(coalesce(v_reason, '')) < 2 then
    raise exception '관리자 닉네임 변경 사유를 2자 이상 남겨야 합니다';
  end if;

  if v_name ~ ('[' || chr(8203) || chr(8204) || chr(8205) || chr(8206) || chr(8207)
                   || chr(160) || chr(65279) || ']')
     or v_name ~ '[[:cntrl:]]'
  then
    raise exception '사용할 수 없는 문자가 있습니다';
  end if;

  select public.current_profile_id() into v_admin_id;

  select display_name
  into v_current
  from public.profiles
  where id = p_profile_id
  for update;

  if not found then
    raise exception 'Profile not found';
  end if;

  if v_current is not null and v_current = v_name then
    return v_current;
  end if;

  if exists (
    select 1 from public.profiles
    where display_name_lower = lower(v_name) and id <> p_profile_id
  ) then
    raise exception '이미 사용 중인 닉네임입니다';
  end if;

  begin
    update public.profiles
    set display_name = v_name,
        display_name_lower = lower(v_name),
        nickname_set = true,
        display_name_changed_at = v_now
    where id = p_profile_id;
  exception
    when unique_violation then
      raise exception '이미 사용 중인 닉네임입니다';
  end;

  update public.monthly_stats
  set nickname = v_name
  where profile_id = p_profile_id
    and month_id = to_char(v_now at time zone 'Asia/Seoul', 'YYYYMM');

  insert into public.profile_display_name_history (
    profile_id,
    changed_by_profile_id,
    old_display_name,
    new_display_name,
    source,
    reason,
    changed_at
  )
  values (
    p_profile_id,
    v_admin_id,
    nullif(v_current, ''),
    v_name,
    'admin',
    v_reason,
    v_now
  );

  return v_name;
end;
$$;

create or replace function public.get_admin_display_name_history(
  p_profile_id uuid default null,
  p_search text default null,
  p_since_days integer default 30,
  p_limit integer default 100
)
returns table (
  history_id bigint,
  profile_id uuid,
  current_display_name text,
  email text,
  old_display_name text,
  new_display_name text,
  changed_by_profile_id uuid,
  changed_by_display_name text,
  source text,
  reason text,
  changed_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  with q as (
    select lower(btrim(coalesce(p_search, ''))) as term
  )
  select
    h.id,
    h.profile_id,
    coalesce(nullif(p.display_name, ''), '익명'),
    p.email::text,
    h.old_display_name,
    h.new_display_name,
    h.changed_by_profile_id,
    coalesce(nullif(actor.display_name, ''), '시스템'),
    h.source,
    h.reason,
    h.changed_at
  from public.profile_display_name_history h
  join public.profiles p on p.id = h.profile_id
  left join public.profiles actor on actor.id = h.changed_by_profile_id
  cross join q
  where public.is_admin()
    and (p_profile_id is null or h.profile_id = p_profile_id)
    and h.changed_at > now() - make_interval(days => greatest(coalesce(p_since_days, 30), 1))
    and (
      q.term = ''
      or position(q.term in lower(coalesce(p.display_name, ''))) > 0
      or position(q.term in lower(coalesce(p.email::text, ''))) > 0
      or position(q.term in lower(coalesce(h.old_display_name, ''))) > 0
      or position(q.term in lower(coalesce(h.new_display_name, ''))) > 0
    )
  order by h.changed_at desc, h.id desc
  limit least(greatest(coalesce(p_limit, 100), 1), 500)
$$;

drop function if exists public.get_admin_users(text, integer);
drop function if exists public.get_admin_users(text, integer, integer);

create or replace function public.get_admin_users(
  p_search text default null,
  p_limit integer default 1000,
  p_offset integer default 0
)
returns table (
  profile_id uuid,
  display_name text,
  email text,
  role text,
  nickname_set boolean,
  max_cpm integer,
  monthly_score integer,
  request_count integer,
  open_signal_count integer,
  display_name_changed_at timestamptz,
  last_active_at timestamptz,
  created_at timestamptz,
  total_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with q as (
    select lower(btrim(coalesce(p_search, ''))) as term
  ),
  matched as (
    select p.*
    from public.profiles p
    cross join q
    where public.is_admin()
      and (
        q.term = ''
        or position(q.term in lower(coalesce(p.display_name, ''))) > 0
        or position(q.term in lower(coalesce(p.email::text, ''))) > 0
      )
  )
  select
    m.id,
    coalesce(nullif(m.display_name, ''), '익명'),
    m.email::text,
    m.role,
    m.nickname_set,
    m.max_cpm,
    coalesce(ms.score, 0),
    (select count(*)::integer from public.sentence_requests r where r.profile_id = m.id),
    (select count(*)::integer from public.abuse_signals a
      where a.profile_id = m.id and a.reviewed_at is null),
    m.display_name_changed_at,
    (select max(tr.created_at) from public.typing_results tr where tr.profile_id = m.id),
    m.created_at,
    count(*) over ()
  from matched m
  left join public.monthly_stats ms
    on ms.profile_id = m.id
   and ms.month_id = to_char(now() at time zone 'Asia/Seoul', 'YYYYMM')
  order by coalesce(ms.score, 0) desc, m.created_at desc
  limit least(greatest(coalesce(p_limit, 1000), 1), 2000)
  offset greatest(coalesce(p_offset, 0), 0)
$$;

comment on table public.profile_display_name_history is
  '사용자 닉네임 변경 이력. 0065 이전 변경은 이전 이름 없이 backfill로만 남는다.';

comment on function public.get_admin_display_name_history(uuid, text, integer, integer) is
  '관리자용 닉네임 변경 이력 조회.';

comment on function public.admin_update_user_display_name(uuid, text, text) is
  '관리자가 사용자 닉네임을 변경하고 이력을 남긴다.';

revoke all on function public.update_my_display_name(text) from public, anon;
revoke all on function public.admin_update_user_display_name(uuid, text, text) from public, anon;
revoke all on function public.get_admin_display_name_history(uuid, text, integer, integer) from public, anon;
revoke all on function public.get_admin_users(text, integer, integer) from public, anon;

grant execute on function public.update_my_display_name(text) to authenticated;
grant execute on function public.admin_update_user_display_name(uuid, text, text) to authenticated;
grant execute on function public.get_admin_display_name_history(uuid, text, integer, integer) to authenticated;
grant execute on function public.get_admin_users(text, integer, integer) to authenticated;

notify pgrst, 'reload schema';
